### ISSUE TITLE
ng serve displays blank page with console errors in the browser

### ISSUE THREAD

**Issue by mike-morr** [pnp/generator-spfx#113]
#### General Information
* [X] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS
* [X] Angular Elements

#### What Version you are running?
* NodeJS: LTS
* NPM: 6.4.1
* @pnp/spfx: 1.4.0
* @angular/cli: 7.0.4

#### Describe your problem
When I use the ngElements template, `ng serve` doesn't work.  It compiles fine in PowerShell with no errors, but when I open the browser the page is blank.  Looking at the console, I get the following:

![image](https://user-images.githubusercontent.com/6625993/48025707-6aee0200-e101-11e8-9125-13e9a3e01d5b.png)

**Comment by StfBauer** [comment]
Thank you @mike-morr we investigate this issue currently. In the meantime, you can run

```sh
ng server --prod
```

You get at least the component loaded.

**Comment by StfBauer** [comment]
Currently, update to version 1.4.1. which from my tests fixed the polyfill handling.
@mike-morr If you still having troubles please let me know and reopen or open another issue. Thank you.

**Comment by ravindracool12** [comment]
blank page displyed after run my new angular project in version 8 and no error show how can i solve it please tell me

**Comment by aishwaryacedcoss** [comment]
blank page displyed after run my new angular project in version 9 and no error show how can i solve it please tell me
