### ISSUE TITLE
Handlebars generator doesn't work

### ISSUE THREAD

**Issue by phawrylak** [pnp/generator-spfx#121]
#### General Information
* [x] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [x] HandlebarsJS

#### What Version you are running?
* NodeJS: 8.12.0
* NPM: 6.4.1
* @pnp/spfx: 1.4.2

#### Describe your problem
When you try to build new project generated by Handlebars generator, you get `ReferenceError: hbsWatch is not defined` error.

**Comment by StfBauer** [comment]
Merged and up for testing - Thank you @phawrylak
