### ISSUE TITLE
Some templates seems use wrong names

### ISSUE THREAD

**Issue by s-KaiNet** [pnp/generator-spfx#131]
#### General Information
* [x] Bug

Under `util.deployTemplates`: 
```javascript
const ejsInject = {
	componentClassName: component.componentClassName,
	componentClassNameKebabCase: paramCase(component.componentClassName),
	componentNameCamelCase: component.componentClassName, // <-- this one is not correct
	componentStrings: component.componentClassName + 'Strings',
	componentPath: component.componentPath,
	componentName: component.componentName
};
```  

According to its name, `componentNameCamelCase` should be initialized with something like `camelCase(component.componentName)`    
SPFx uses camel case component name transformation in scss files, but code above injects `componentClassName` instead in scss files which is not correct.

**Comment by StfBauer** [comment]
In general, all templates have been tested on a case-sensitive file system. the suggestion might cause issues. While it might look not correct it resolve issues on Linux and OSX.

@s-KaiNet: Which generator do you think to have this issue?

**Comment by s-KaiNet** [comment]
I just wanted to point out, that `componentNameCamelCase` is not a correct name, because it holds a value of `component.componentClassName`, but the name `componentNameCamelCase` suggests that this property holds camel cased component name. Additionally, we have the same value in `componentClassName: component.componentClassName` property. What is the reason to duplicate it in another property with a different name? I found it confusing.    

From my POV all blocks with `<%= componentNameCamelCase %>` should be renamed to `<%= componentClassName%>`, because that's the actual value which is rendered. `componentNameCamelCase` in turn, should be converted to valid camel cased component name instead.  

Do you agree?

**Comment by StfBauer** [comment]
No, because this is related to an unfixed bug in SPFx. Once this is fixed we are able to change it back.
[This one](https://github.com/SharePoint/sp-dev-docs/issues/2481) for example but there are more than just this.

**Comment by s-KaiNet** [comment]
Ok, then I have a need to add a property to `ejsInject` variable, with a value equal to camel-cased component name. Since `componentNameCamelCase` is already taken and I can't change it, what will you suggest?

**Comment by StfBauer** [comment]
Depends on what you try to accomplish? You can pass whatever you like to esinject.

**Comment by s-KaiNet** [comment]
I'm just trying to find the correct name for the property since `componentNameCamelCase` isn't available for modification.   

`componentNameCamelCase2`, 'componentNameCamelCaseProper'? :) Doesn't look good at all. `componentNameCamelCase` is the best, but it's value isn't good for me.

**Comment by s-KaiNet** [comment]
I can introduce `componentNameCamelCaseTemp` and remove it later when the appropriate bug in SPFx will be fixed. Of course, if it works for you.

**Comment by s-KaiNet** [comment]
Closed accidently.

**Comment by StfBauer** [comment]
Even the none CamelCase ComponentName is camelcase as far as I remember.
@s-KaiNet if you think about the style linter it might be useful to add it just to the addons.

**Comment by s-KaiNet** [comment]
In style lint, I have to provide own `{componentClassName}.module.scss`, because OOB ones have lint errors :). Just minor ones, but anyway. That's why I can't store it in addons. `ComponentName` isn't camel-cased, unfortunately, that's why I'm asking about all this stuff.

**Comment by s-KaiNet** [comment]
We should make an agreement on the right approach because it's kind of block for me for a moment.   

I'm going to add a property called `componentNameCamelCaseTemp` to `ejsInject` which holds the value of 'camelCased(component.componentClassName)'. That's a temporary solution since SPFx bug isn't fixed.  

Do you approve it?

**Comment by StfBauer** [comment]
Well, there is another thing that blocks you in the default generator as well. 

While the template variables state to use CamelCase neither the web part nor the CSS pass in camel case component name. Those are always named as the variable that will be passed in as the web part name.

I created already a couple of web parts but neither of those used CamelCase for styling and only in JavaScript.

Just create a simple `@microsoft/sharepoint` solution and pass in the following values:

**Testcase1:** helloWorld
**Testcase2:** helloWorld2
**Testcase3:** HelloWorld3

and then check the result in CSS.

**Comment by s-KaiNet** [comment]
So in my case (Windows) class names are   

`.helloWorld`, `.helloWorld2`, `.helloWorld3`  

I guess on OSX they are different?

**Comment by s-KaiNet** [comment]
`.helloWorld`, `.helloworld2`, `.helloworld3`   

Is it different for you?

**Comment by StfBauer** [comment]
@s-KaiNet No same result what you pass in comes out.

**Comment by s-KaiNet** [comment]
reopen

**Comment by s-KaiNet** [comment]
@StfBauer `Helloworld3` for you because of OSX?

**Comment by StfBauer** [comment]
Seems to be that it was related to another issue in the past and now it seems to be fixed. If so I will update the templates because of the property of camelCase class name already exists and no extra code is needed.

Thanx for letting me know.

First test on Windows: helloWorld
<img width="747" alt="screenshot 2018-12-05 at 20 32 38" src="https://user-images.githubusercontent.com/5503835/49539007-f60f1300-f8cc-11e8-8544-e181fab2a0cb.png">

Second test on Windows: helloworld2
<img width="511" alt="screenshot 2018-12-05 at 20 33 53" src="https://user-images.githubusercontent.com/5503835/49539065-222a9400-f8cd-11e8-93e9-05b72a58f17d.png">

Third test on Windows: Helloworld3
<img width="614" alt="screenshot 2018-12-05 at 20 35 47" src="https://user-images.githubusercontent.com/5503835/49539181-5ef68b00-f8cd-11e8-8988-8d506be7ea31.png">

Third test on OSX: Helloworld4
<img width="696" alt="screenshot 2018-12-05 at 20 41 54" src="https://user-images.githubusercontent.com/5503835/49539583-3f139700-f8ce-11e8-8193-3b1eebb45946.png">
