### ISSUE TITLE
PnP Property Controls is not under react libs

### ISSUE THREAD

**Issue by s-KaiNet** [pnp/generator-spfx#133]
#### General Information
* [x] Usage

#### Specific generator
* [x] Addons

If you select "No Framework" or "Knockout", `PnP Property Controls` are available under additional libraries to include. Since it's react based module, does it make sense to show it only if React framework was selected and not show for "No Framework" and "Knockout" (the same way as "PnP Reusable Controls")?

**Comment by StfBauer** [comment]
Property controls can always be used in any project since the web part always render inside a React container.

**Comment by s-KaiNet** [comment]
Then the question is why "PnP Reusable Controls" is not listed if I select "No Framework"? Following the same logic, the web part always renders inside a React container.

**Comment by StfBauer** [comment]
Property pane controls are precompiled and rendered directly in the SPFx framework at runtime. The other need to be compiled during the Gulp Build chain.

**Comment by s-KaiNet** [comment]
Ah, I see.. thank you. In that case, unfortunately, nothing can be changed here.
