### ISSUE TITLE
"No matching version found for ts-loader@^3.5.3" when installing project dependencies

### ISSUE THREAD

**Issue by wy62** [pnp/generator-spfx#150]
#### General Information
* [ ] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request
* [x] Bug

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS
* [x] VueJS

#### What Version you are running?
* NodeJS: 8.15.0
* NPM: 6.4.1
* @pnp/spfx: 1.6.1

#### Describe your problem
When attempting to create a new project, npm install fails with the error:

> No matching version found for ts-loader@^3.5.3

[According to here](https://www.npmjs.com/package/ts-loader) there is no version 3.5.3 of ts-loader. I'm relatively new to spfx and client side dev so not sure what other information to provide.

![capture1](https://user-images.githubusercontent.com/38424552/52305859-22f3ab00-298e-11e9-9838-1b846cb1334b.PNG)

![capture2](https://user-images.githubusercontent.com/38424552/52305872-2be47c80-298e-11e9-8a7a-0d23b34f964e.PNG)

**Comment by wy62** [comment]
I can confirm that making this change in `package.json` and running `npm install` again resolved this problem. Thanks.

**Comment by StfBauer** [comment]
Thank you @wy62 - it will be fixed in the next release of the generator.

**Comment by StfBauer** [comment]
@wy62 Your issue is not fixed in 1.6.2.
