### ISSUE TITLE
Missing Angular-Elements folder when creating  webpart "Sharepoint 2016 onwards, including 2019 and SPO"

### ISSUE THREAD

**Issue by gonadn** [pnp/generator-spfx#151]
#### General Information
* [ ] Usage
* [*] Development
* [ ] Documentation
* [ ] Feature Request

Specific generator:
* [*] Angular Elements

 Version:
* NodeJS: v8.15.0
* NPM: v6.7.0
* @pnp/spfx: latest 1.6.1

Hi

Iam trying to create Angular Element project/solution "SharePoint 2016 onwards, including 2019 and SharePoint Online". 
When i create the solution with command "yo @pnp/spfx" i end up with only one project folder and angular-elements project folder are missing, se pic below:

![image](https://user-images.githubusercontent.com/3224441/52524245-47f06280-2c9b-11e9-9f5f-7cf3d2abc5b0.png)

Looks like @pnp/spfx generator is not creating the Angular-Element project/solution at all....

Here is step by step how i create the webpart:
Step1:
![image](https://user-images.githubusercontent.com/3224441/52524139-0317fc00-2c9a-11e9-8dbc-455c4cc11728.png)

Step2:
![image](https://user-images.githubusercontent.com/3224441/52524148-1c20ad00-2c9a-11e9-8dd0-145638d83953.png)

Step3:
![image](https://user-images.githubusercontent.com/3224441/52524150-22af2480-2c9a-11e9-99d1-0d0a80401941.png)

Step4:
![image](https://user-images.githubusercontent.com/3224441/52524151-2e025000-2c9a-11e9-9d17-26a48dc0dd40.png)

Step5:
![image](https://user-images.githubusercontent.com/3224441/52524153-35c1f480-2c9a-11e9-80e2-632522e3d803.png)

Step6:
![image](https://user-images.githubusercontent.com/3224441/52524157-3f4b5c80-2c9a-11e9-8899-32002a3c6110.png)

Step7:
![image](https://user-images.githubusercontent.com/3224441/52524204-d6b0af80-2c9a-11e9-8211-b98a4827955a.png)

**Comment by StfBauer** [comment]
Do you have the Angular CLI Install? Have you got any error during project creation?

**Comment by gonadn** [comment]
yes @angular/cli is installed...

**Comment by StfBauer** [comment]
Hi Adnan,

Which version of the CLI is installed? 7+ or an older version?

![screenshot 2019-02-09 at 21 00 46](https://user-images.githubusercontent.com/5503835/52525712-d53cb280-2cad-11e9-98c2-a0a5f8f8ac6c.png)

Have you got any error during the project creation?

Thank you.

**Comment by gonadn** [comment]
Running Angular-cli version:
![image](https://user-images.githubusercontent.com/3224441/52525748-7d527b80-2cae-11e9-91f4-bd8fd5014b08.png)

No error during creation of project....

**Comment by gonadn** [comment]
i just removed angular-cli v7.3.1 and installed v7.0.3, got same issue, missing AE project , no error during creation of project...

**Comment by StfBauer** [comment]
@gonadn Found the issue: "Sharepoint 2016 onwards, including 2019 and SPO" is not supported with Angular Elements because it uses the outdated - SPFx 1.2.0

You have to choose at least: "SharePoint 2019 onwards, including SharePoint Online"

You will see this during installation through the following message:
![screenshot 2019-02-09 at 21 25 16](https://user-images.githubusercontent.com/5503835/52525907-3a45d780-2cb1-11e9-984e-354e2125b996.png)

I will update the documentation in this regards.

**Comment by gonadn** [comment]
If i choose "SharePoint 2019 onwards, including SharePoint Online" will it work on SharePoint2016 on-prem?

**Comment by StfBauer** [comment]
No SharePoint 2016 on-premise will not support newer versions of SPFx anymore as far as I know. So you will have to stay with SPFx 1.2.0

The generator flows the two project approach by Voitanos and Andrew Connell:
https://www.voitanos.io/blog/howto-angular-elements-in-sharepoint-framework-projects-two-projects

You only can set up the projects manually: https://www.voitanos.io/blog/howto-angular-elements-in-sharepoint-framework-projects-two-projects

**Comment by gonadn** [comment]
So retarded of supporting not supporting, sp16,19 or SPO...!

**Comment by gonadn** [comment]
I think you should consern litle on how to fix all bugs, you are just interested in clsing the issues, and you know that all this Angular-Elemnt stuff is just a crap not working as asspected in SPFX. Anuf bullshitt about this and that is not supported. 

And another thing, if i need to choose "SharePoint 2019 onwards, including SharePoint Online" why do you have option for SharePoint 2016 when it is not working on any case for those who will try to create webpart for SP2016. Lack of information, and just messy playground with shitt code. 

Better that you and all of you behind this, cut the crap and do not put thing dosent work....

And for you Stefan Bauer, you should consider to solve problems, not closig the issues. You have done that many other case, your first try is to just close issue as fast you can....
