### ISSUE TITLE
If you select a react app it's impossible not to have Jest included

### ISSUE THREAD

**Issue by baywet** [pnp/generator-spfx#157]
#### General Information
* [x] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [x] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: 8.15.0
* NPM: 6.4.1
* @pnp/spfx: 1.6.1

# Repro
1. yo @pnp/spfx
1. select spo
1. select reactjs
1. do not select any library
1. do not select any vetting

The only choice you are given is to include Jest.
![image](https://user-images.githubusercontent.com/7905502/52818740-9031cb00-3075-11e9-98c3-a4ea2dc65bbe.png)

# Expected
I'd like to be able not to select Jest if I don't want to.

**Comment by StfBauer** [comment]
Good point we should flip it to a 'choice' option in next release.
