### ISSUE TITLE
Missing gulp-sequence in package.json

### ISSUE THREAD

**Issue by gautemo** [pnp/generator-spfx#158]
#### General Information
* [x] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [x] Vue
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: 8.13
* NPM: 6.2.0
* @pnp/spfx: 1.6.2

#### Describe your problem
After initializing the project and running gulp clean I get the following error;
"Error: Cannot find module 'gulp-sequence'"
Which is fixed by running: "npm i gulp-sequence --save"
But it would be nice if it already was added to package.json and installed at the initial npm install done by the generator.

**Comment by StfBauer** [comment]
I created a new project using version 1.6.2 and the gulp-sequence was included in the package.json.

Have you got any other error during the installation?

**Comment by StfBauer** [comment]
@gautemo Found the issue. It occurs when no additional add-on was selected. Should be fixed soon.

**Comment by joelfmrodrigues** [comment]
Just had the same issue last night and I also haven't selected an add-on
