### ISSUE TITLE
Cannot select framework

### ISSUE THREAD

**Issue by Leif-Frederiksen** [pnp/generator-spfx#162]
#### General Information
* [x] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: 
* NPM:
* @pnp/spfx: 

>--------------- DELETE THIS BEFORE SUBMITTING ---------------
>
> Execute the following scripts to get these informations
> 
> To get NodeJS version: 
>     ```node --version```
> 
> To get NPM version: 
>     ```npm --version```
>
> To get NPM version: 
>     ```npm list -g @pnp/generator-spfx --depth=0```
> 
> --------------- DELETE THIS BEFORE SUBMITTING ---------------

#### Describe your problem
>--------------- DELETE THIS BEFORE SUBMITTING ---------------
>
> Please provide as many information as possible to make it easy to support or understand your request.
>
> *For usage issues:* Please describe exactly the steps to reproduce
> *For development issues:* In cae you have a problem during development please provide a link to the your fork or source code if possible 
> *For documentation Issues:* Please provide a link to the documentation
> *For feature request:* Please provide links and use cases of you feature
>
>--------------- DELETE THIS BEFORE SUBMITTING ---------------

**Comment by StfBauer** [comment]
Can you please provide a bit more details. Thank you.
