### ISSUE TITLE
VueJS Generator DIST issue on build

### ISSUE THREAD

**Issue by BlueBird67** [pnp/generator-spfx#176]
#### General Information
* [X ] Usage

#### Specific generator
* [X ] VueJS

#### What Version you are running?
* NodeJS: 8.15.1
* NPM: 6.4.1
* Vue : 2.6.1
* @pnp/spfx: Last one

Hello, for Gulp build with VueJS Generator, I need to add 
`"baseUrl": "."`
on **CompilerOptions** in **tsconfig.json** file.

Otherwise, I got several mess with DIST folder sub-structure on build, and webpart is not working on browser, as it can't find js main file.

**Comment by StfBauer** [comment]
Thank you for that info @BlueBird67 

Can you please share your complete tsconfig.json?
What have you generated? 
SharePoint 2016, SharePoint 2019, SPO?

Does the web part worked for you after you make those adjustments?

**Comment by StfBauer** [comment]
I create a sample web part using SPO and deployed it. Everything seems to work. I was even able to add the sppkg file to the App Catalog and was able to deploy it.

**Comment by StfBauer** [comment]
Closed - the problem couldn't be reproduced.
