### ISSUE TITLE
Microsoft Graph Api

### ISSUE THREAD

**Issue by sandippal972258** [pnp/generator-spfx#183]
Hello guy's

I am using graph api with C# console application and i am create microsoft planner with that.
I have register app with AD and i got client id and client secret. Now i am using those client id and secret for create ms planner for particular group and i am getting access denied error.

I can get users of the group but while i am going to create ms plan, its showing access denied error.

I have already add  group.read.write.all permission in my app while i had register that.
Can any buddy help me?

MY ERROR :

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>

**Comment by StfBauer** [comment]
Sorry, @sandippal972258, unfortunately, I cannot help you with this issue. This issue list is only related to JavaScript and SPFx development.

The best bet is to copy this issue over to StackOverflow and tag it as 'microsoft-graph'.

https://stackoverflow.com/questions/tagged/microsoft-graph 

Thank you for your understanding.

**Comment by sandippal972258** [comment]
Ok Thanks @StfBauer
