### ISSUE TITLE
 Cannot find module 'gulp-sequence'

### ISSUE THREAD

**Issue by gauravgoyal5** [pnp/generator-spfx#191]
#### General Information
* [x] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS:  8.13.0
* NPM: 6.9.1-next.0
* @pnp/spfx: 1.8.1.

#### Describe your problem

I am creating SPFx project for SP2016, SP2019 & SP Online.

![image](https://user-images.githubusercontent.com/6926513/61593908-658b0600-ac03-11e9-97b1-186d741ea734.png)

Getting error when using command gulp serve.
![image](https://user-images.githubusercontent.com/6926513/61593934-a2ef9380-ac03-11e9-9377-9c21028ae2a1.png)

**Comment by StfBauer** [comment]
Thank you @gauravgoyal5  for letting us know. Are you able to share your package.json? or if now do you find a reference to gulp-sequence in the package file?

**Comment by gauravgoyal5** [comment]
Hi @StfBauer , 
No, I am not able to find gulp-sequence in the package file. I installed it manually.
Now I am running the command "gulp serve" & getting the issue :
![image](https://user-images.githubusercontent.com/6926513/61776942-ac524900-ae19-11e9-92aa-05dd2c47851a.png)

Here is the details of package.json file 
`{
  "name": "greetings",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "./node_modules/.bin/jest --config ./config/jest.config.json",
    "test:watch": "./node_modules/.bin/jest --config ./config/jest.config.json --watchAll"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-lodash-subset": "~1.1.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0-0",
    "@microsoft/sp-webpart-base": "~1.1.0",
    "@types/es6-promise": "0.0.33",
    "@types/webpack-env": "1.13.1"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.1.0",
    "@microsoft/sp-module-interfaces": "~1.1.0",
    "@microsoft/sp-webpart-workbench": "~1.1.0",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "@voitanos/jest-preset-spfx": "^1.1.0",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "gulp-sequence": "^1.0.0",
    "jest": "^23.6.0"
  }
}
`
