### ISSUE TITLE
PrimeVUE components gives errors

### ISSUE THREAD

**Issue by nsksaisaravana** [pnp/generator-spfx#192]
#### General Information
* [ ] Usage
* [* ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS
* [ *] VUE JS

NodeJS: 8.13.0
NPM: 6.9.1-next.0
@pnp/spfx: 1.8.1.

Describe your problem

I am using primevue components and it is giving me errors. Below is my implementation in the webpart.ts

import {Button} from 'primevue/button';
import {Calendar} from 'primevue/calendar';
import {InputText} from 'primevue/inputtext';

//Vue.component('Button', Button);

Vue.component('InputText', InputText);
Vue.component('Button', Button);

As soon as I add the above code, I am getting below error.

[SPLoaderError.loadComponentError]:
***Failed to load component "886a9b69-3b82-4b20-8f2e-c63b10506bee" (HelloWorldWebPart).
Original error: ***Failed to load entry point from component "886a9b69-3b82-4b20-8f2e-c63b10506bee" (HelloWorldWebPart).
Original error: Error loading https://component-id.invalid/886a9b69-3b82-4b20-8f2e-c63b10506bee_0.0.1
	Module parse failed: Unexpected token (13:16)
You may need an appropriate loader to handle this file type.
|         listeners() {
|             return {
|                 ...this.$listeners,
|                 input: event => this.$emit('input', event.target.value)
|             };

***INNERERROR:
***Failed to load entry point from component "886a9b69-3b82-4b20-8f2e-c63b10506bee" (HelloWorldWebPart).
Original error: Error loading https://component-id.invalid/886a9b69-3b82-4b20-8f2e-c63b10506bee_0.0.1
	Module parse failed: Unexpected token (13:16)
You may need an appropriate loader to handle this file type.
|         listeners() {
|             return {
|                 ...this.$listeners,
|                 input: event => this.$emit('input', event.target.value)
|             };
***CALLSTACK:
Error
    at SPLoaderError.SPError [as constructor] (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:8390:24)
    at new SPLoaderError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:4036:28)
    at Function.ErrorBuilder.buildErrorWithVerboseLog (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:3789:21)
    at Function.ErrorBuilder.buildLoadComponentError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:3697:21)
    at https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:6275:47

**Comment by StfBauer** [comment]
At the moment only native VueJS is supported and haven’t been tested with such 3rd party Vue component libraries.

It seems like there are some additional steps to do to make the integration possible in VueJS using the CLI.

If there is more demand to support this we might try to embed it too.

**Comment by nsksaisaravana** [comment]
@StfBauer Thanks for your immediate action, it would be awesome to have those components.

**Comment by StfBauer** [comment]
I cannot promis anything right now but if you get it working in the mean time you are more than welcome to share your findings.

It may be just a project that shows what needs to be addressed in the setup to make this work.

If you are feeling you can integrate this yourself in the generator then feel free to submit a PR.

**Comment by nsksaisaravana** [comment]
Thanks @StfBauer . I spend some time on it and below are my observation.

1. I could able to load PrimeVue CSS by SPComponentLoader.loadCss.

![image](https://user-images.githubusercontent.com/17681573/63242490-e426a200-c29a-11e9-8a0e-bb588494fbda.png)


2. The respective component javascript file is not getting loaded, even though i import the primevue component.

![image](https://user-images.githubusercontent.com/17681573/63242571-264fe380-c29b-11e9-8189-026f41e4f403.png)

3. Please check the Network tab.

![image](https://user-images.githubusercontent.com/17681573/63242638-5f885380-c29b-11e9-8b42-fb47bd99b3cb.png)

**Comment by nsksaisaravana** [comment]
@StfBauer @AJIXuMuK I have created a repository for it https://github.com/nsksaisaravana/TheHub . I have used primevue, v-runtime-template and both are not working. Both supports typescript. I need to convert string HTML to proper HTML so I used v-runtime-template and for the components I used primevue.

**Comment by nsksaisaravana** [comment]
@AJIXuMuK i tried to use the dropdown component and it is not working. pleas check the screenshot below. repo is available in the https://github.com/nsksaisaravana/TheHub.

![image](https://user-images.githubusercontent.com/17681573/63668593-e2208e00-c81a-11e9-9498-cfa495a8f85f.png)

**Comment by nsksaisaravana** [comment]
Now it is working, I am closing.

**Comment by nsksaisaravana** [comment]
all good now
