### ISSUE TITLE
Handlebars Error with Partial

### ISSUE THREAD

**Issue by markgab** [pnp/generator-spfx#204]
#### General Information
* [ ] Usage
* [x] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [x] HandlebarsJS

#### What Version you are running?
* NodeJS: v10.16.3
* NPM: 6.9.0
* @pnp/spfx: 1.9.1 

#### Describe your problem

I'm receiving an error at runtime when attempting to reference a Handlebars partial in my template. 

Sometimes I get an error when I attempt to register the partial:

>handlebars__WEBPACK_IMPORTED_MODULE_4__.registerPartial is not a function

other times I get and error during render

>The partial partialtest could not be found

#### How to recreate

Create a new webpart project with Handlebars as the framework. Use defaults for everything else.

Add file partialtest.hbs to the components folder with this markup:

`<div>My Partial</div>`

Register the Handlebars partial in the webpart:

`
var PartialTemplate = <HandlebarsTemplateDelegate>require('./components/partialtest.hbs');
Handlebars.registerPartial('partialtest', PartialTemplate);
`

Call the partial from your web part handlebars template:

`
  {{> partialtest }}
`

Run the web part on the local workbench.

I am having a similar problem with Handlebars helpers, but I figured that would be a separate item on the issue tracker. Thanks for your excellent work, the generator is a big help!

Bests,

Mark Gabriel

**Comment by StfBauer** [comment]
Hi @markgab thank you for reporting this issue. We will look into it. Could be that there is some special way to use partials. I will let you know.

**Comment by StfBauer** [comment]
@markgab Thank you once again. I reviewed your issue and it seems like we have to update and replace the webpack handlebars loader and replace it with another option

It should be included in the next release.

In the meantime, you can look at this: https://github.com/pcardune/handlebars-loader

This will be the new one that will be included in an upcoming release.

**Comment by markgab** [comment]
Thanks Stefan, I'll check out the other loader.

**Comment by StfBauer** [comment]
@markgab should be fixed in the current version.
