### ISSUE TITLE
!!! Project needs to be upgraded !!!

### ISSUE THREAD

**Issue by ldaviswtg** [pnp/generator-spfx#205]
#### General Information
* [x ] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [x ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: v10.16.1
* NPM: 6.11.3
* @pnp/spfx: 1.9.1

**I get the following for 'yo @pnp/spfx'**

 "Generator:     PnP Community SPFx Generator
 Author:        Office 365 / SharePoint PnP Core Team
 Maintainers:   Stefan Bauer
 Contributors:  Bill Ayers, Vincent Biret, Sergei Sergeev, Paweł Hawrylak, Chris Kent, Alex Terentiev
 Version:       1.9.1

 Based on  @microsoft/generator-sharepoint version: 1.9.1

!!! Project needs to be upgraded !!!
> Please review the file  upgrade-log.md  in the project root."

**Upgrade-log.md only contains "null"**

**Comment by StfBauer** [comment]
Do you find any .yo-rc file in the folder you execute the generator or the parent folder?

**Comment by ldaviswtg** [comment]
No.

**Comment by ldaviswtg** [comment]
Got the generator to run by using the --skip-version-check option

**Comment by StfBauer** [comment]
So for my understanding you executed:

```shell
yo @pnp/spfx --skip-version-check
```

Have you executed it like this on an existing or on a new project?

I ran a quick check and this was my result on the current version.

<img width="784" alt="Screenshot 2019-09-18 at 19 29 46" src="https://user-images.githubusercontent.com/5503835/65171242-b4f68280-da4a-11e9-9a33-237ee05317fa.png">

Thank you for you input.

**Comment by StfBauer** [comment]
Closed due inactivity.
