### ISSUE TITLE
Support for Svelte

### ISSUE THREAD

**Issue by BassemNKhalil** [pnp/generator-spfx#215]
#### General Information
* [ ] Usage
* [ ] Development
* [ ] Documentation
* [x] Feature Request

#### Specific generator
NA

#### What Version you are running?
NA

#### Describe your problem
Reading up on Svelte which got me wondering how much work it would be to incorporate a different framework into SPFx (same as angular or handlebars). Interested to help as much as I can, looking for where to start (and whether that seems worthy to the community to expand SPFx into more frameworks).

**Comment by StfBauer** [comment]
@BassemNKhalil The easiest way to get your request running is when you start to integrate this framework in a new SPFx project based on a "No Framework-based" project.

The integration is always the harder part. Once you have a sample project in SPFx up and running please add a link to your repo here.

I personally haven't heard yet about this framework yet. I always learn a lot by things I like to try out so it only has benefits for you and maybe for others too.

**Comment by BassemNKhalil** [comment]
Fair enough. I'll close this off for now.

Thanks,
B

**Comment by StfBauer** [comment]
Thank you. Let me know if I can assist you somehow.

**Comment by kayodebristol** [comment]
@StfBauer  @BassemNKhalil 
Will gladly create a new issue if that's best. 
Here's a [template](https://github.com/sp-sveltejs/spfx-svelte-templates) svelte-webpart. Even though it's basic, the elegance of using [svelte](https://svelte.dev) with SPFx still comes across. Please, let me know what I can do further svelte support in SPfx. Many thanks.

**Comment by StfBauer** [comment]
We accept PR’s too 😀

**Comment by kayodebristol** [comment]
Got it to work here -> [svelte-webpart-online](https://github.com/sp-sveltejs/spfx-svelte-templates/tree/master/svelte-webpart-online). 
When doing a gulp serve, I have to manually copy the .svelte file in the lib\webpart\[webpartName] folder. 

I'll try to create a PR after some tweaks. 

Testing a generator config looks like a beast. Well, let no good deed go unpunished.
