### ISSUE TITLE
Postinstall patch script unreliable

### ISSUE THREAD

**Issue by JakeStanger** [pnp/generator-spfx#216]
#### General Information
* [x] Usage
* [x] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: v.10.18.0
* NPM: 6.13.4 
    - (Yarn v1.19.2)
* @pnp/spfx: v1.10.2

#### Describe your problem

The postinstall patch script is unreliable, since it relies on all the dependency modules being installed inside the package's own install directory. Installing with NPM globally will yield this result, however installing locally with either NPM or Yarn, or installing globally with Yarn, will not.

Instead, the modules are installed at the root of `node_modules` meaning [this path](https://github.com/pnp/generator-spfx/blob/master/lib/patch.js#L11) (and various other paths) are no longer correct. This causes the package to fail installation.

```
error C:\Users\jake.stanger\AppData\Local\Yarn\Data\global\node_modules\@pnp\generator-spfx: Command failed.
Exit code: 1
Command: node lib/patch.js
Arguments:
Directory: C:\Users\jake.stanger\AppData\Local\Yarn\Data\global\node_modules\@pnp\generator-spfx
Output:
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, mkdir 'C:\Users\jake.stanger\AppData\Local\Yarn\Data\global\node_modules\@pnp\generator-spfx\node_modules\@microsoft\generator-sharepoint\lib\generators\applicationCustomizer\templates\react'       at Object.mkdirSync (fs.js:757:3)
    at Object.<anonymous> (C:\Users\jake.stanger\AppData\Local\Yarn\Data\global\node_modules\@pnp\generator-spfx\lib\patch.js:123:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

The script could use `require.resolve` to get the path for the the module. The downside to this is that the generator will be modifying an install of the base generator that may not be associated with this generator. The upside is it should always work.

**Comment by StfBauer** [comment]
Thank you very much @JakeStanger. I was able to reproduce the issue using yarn and pnpm. Those are the affected package manager.

**Comment by StfBauer** [comment]
@JakeStanger Now it is getting really interesting cause `require.resolve` doesn't do what it actually should do.

```javascript
console.log('MODULE SEARCH PATHs ::::\n\t', module.paths);
console.log('Current __dirname\n\t',__dirname);
console.log('process.cwd() ::::\n\t', process.cwd());

const basePath = require.resolve.paths('@microsoft/generator-sharepoint')
    .filter(item => {

        const requestPath = path.join(
            item,
            '/@microsoft/generator-sharepoint'
        );
        if (fs.existsSync(requestPath)) {
            console.log('FOUND:\n\t', requestPath);
            return requestPath;
        } else {
            // console.log('not found in ', path.join(
            //     item,
            //     '@microsoft/generator-sharepoint'
            // ))
        }
    });

console.log('BASEPATH Found ::::\n', basePath);

console.log('Require Resolve  ::: require.resolve(\'@microsoft/generator-sharepoint\') RESULT:::');
console.log('Require Resolve  :::\n', require.resolve('@microsoft/generator-sharepoint'));
```

The result is that require.resolve only searches the lib folder but not the others folder. 

<img width="1031" alt="Screenshot 2019-12-20 at 17 42 50" src="https://user-images.githubusercontent.com/5503835/71269730-4c23ec80-2350-11ea-98a8-36d5bd77df69.png">

This could be fixed by searching for one of the matching paths but yeah I do not really like it as a solution.

Any other suggestion in mind?

**Comment by JakeStanger** [comment]
This does seem odd. Perhaps `require.resolve` doesn't actually work as we expect it to. Are you able to just `require("@microsoft/generator-sharepoint") in the script?

I wonder if you could use some other module resolution system? 

I think a nice solution is going to be a little hard to come by since the script is pretty hacky in the first place. I would agree there has to be a better approach than just trying every path.

> I checked it with require.resolve('fs') too and this works neither.

Sorry, I can't quite make sense of this. Do you mean resolving `fs` did or did not work?

**Comment by StfBauer** [comment]
require.resolve('fs') do not work as I tested. I will see how to get this resolved.

This

```javascript```
console.log('MODULE SEARCH PATHs ::::\n\t', module.paths);
```

Are actually configured to be the well-known paths that should get considered to evaluate the path. ATM the easiest way to filter those out with a try.

**Comment by StfBauer** [comment]
@JakeStanger I guess I fixed the issue now. The tests I did were at least promising. I published a new alpha version that should work now with yarn and pnpm.

Can you test run this too?


```shell
yarn add global @pnp/generator-spfx@1.10.3-alpha5
```

Thanx.

**Comment by JakeStanger** [comment]
Appears to install and run without a problem, excellent. 

If you can give me a couple of hours I will try including the alpha version as the dependency of another generator just to confirm the problem is 100% gone.

**Comment by StfBauer** [comment]
@JakeStanger Great thanks. Just out of curiosity. What does this generator do? ;)

**Comment by JakeStanger** [comment]
Okay just installed the alpha version as a dep and it worked fine. Awesome!

We use a generator internally that first runs this generator and then adds some company specific patches such as extra configs etc.

**Comment by ontoneio** [comment]
Has this pull request been made? I am having a similar issue.
Also is this just for yarn and pnpm?

**Comment by ontoneio** [comment]
Here is the error I am getting when trying to run the generator.

```
Error: ENOENT: no such file or directory, mkdir 'C:\Users\jonmitch\AppData\Roaming\npm-cache\_npx\28760\node_modules\@pnp\node_modules\@microsoft\generator-sharepoint\lib\generators\applicationCustomizer\templates\react'
    at Object.mkdirSync (fs.js:757:3)
    at Object.<anonymous> (C:\Users\jonmitch\AppData\Roaming\npm-cache\_npx\28760\node_modules\@pnp\generator-spfx\lib\patch.js:175:8)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pnp/generator-spfx@1.10.3-alpha10 postinstall: `node lib/patch.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @pnp/generator-spfx@1.10.3-alpha10 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Latest patch doesn't seem to work for me.

**Comment by StfBauer** [comment]
I checked npm, yarn and pnpm in this alpha version and it worked without any problem on Windows + Mac.

@ontoneio Could it be you ran npx instead of npm?

**Comment by JakeStanger** [comment]
Awesome, thanks!
