### ISSUE TITLE
Sample of azure-pipelines.yml not found

### ISSUE THREAD

**Issue by Laul0** [pnp/generator-spfx#220]
#### General Information
* [ ] Usage
* [ ] Development
* [x] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: 
* NPM:
* @pnp/spfx: 

#### Describe your problem

The link provided into the documentation to redirect users to the Sample of `azure-pipelines.yml` is not found:

![Screen Shot 2020-01-09 at 10 05 16](https://user-images.githubusercontent.com/15279205/72078683-905b3a80-32c7-11ea-80cf-43dcc654cac9.png)

The modification should be the following one:

```diff
- Update your `azure-pipelines.yml` to match the [following sample](https://github.com/SharePoint/sp-dev-build-extensions/samples/azure-devops-ci-cd-spfx/azure-pipelines.yml)
+ Update your `azure-pipelines.yml` to match the [following sample](https://github.com/SharePoint/sp-dev-build-extensions/blob/master/samples/azure-devops-ci-cd-spfx/azure-pipelines.yml)
```

**Comment by StfBauer** [comment]
Thank you for reporting those dead links.

Since this link points to another repository I the links for now to the full sample-path.

@baywet Can you the documentation and if the links are still correct. Can you please fix those.

**Comment by baywet** [comment]
Good catch @Laul0 !
Do you mind issuing a PR that only changes the link or should I fix it?

**Comment by StfBauer** [comment]
@baywet Would be great if you are able to fix the link since you are/was also involved in the other project too. I was not able to find the correct link and it would be great to have those more "flexible" so that we don't produce potential dead links in the future.

Thank you!

**Comment by baywet** [comment]
PR submitted!
