### ISSUE TITLE
Unable to install generator

### ISSUE THREAD

**Issue by vaderj** [pnp/generator-spfx#228]
#### General Information
* [ ] Usage
* [x ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: v10.16 & v10.17
* NPM: 6.12.0 & 6.11.3
* @pnp/spfx:  UNABLE TO INSTALL 
have tried versions: 
           1.11.0, 
           1.10.2,
           1.10.1
           1.10.0
           1.9.1
           1.9.0

#### Describe your problem

I have tried this as administrator on both Server 2012 and Windows 10 (both x64)
Every time I attempt to install globally, it fails:
npm install -g @pnp/generator-spfx

Generated log attached
[2020-02-04T18_38_56_607Z-debug.log](https://github.com/pnp/generator-spfx/files/4155279/2020-02-04T18_38_56_607Z-debug.log)

Screenshot:
![image](https://user-images.githubusercontent.com/5408195/73775898-a24fc200-473b-11ea-9002-bbcb815cfce4.png)

As the errors keep complaining about lodash, I installed lodash globally via NPM but that had 0 effect on anything

**Comment by StfBauer** [comment]
@vaderj  Have you tried to install @microsoft/generator-sharepoint? Does this work?

**Comment by vaderj** [comment]
Yes, the @microsoft\generator-sharepoint is installed globally and installs and the Yo generator functions without issue.

I am behind a corporate firewall, but that isn't preventing any other functions with NPM and I was seeing the same issues last night when I brought my work laptop home.

**Comment by StfBauer** [comment]
@vaderj Than you for the update. Can you try to execute the following command.

```sh
yo doctor
```

Another thing to check is if you use the default registry or something else from AzureDevOps for example.
When you execute the following command:

```sh
npm get registry
```

You should get the following result:

```
https://registry.npmjs.org/
```

**Comment by vaderj** [comment]
![image](https://user-images.githubusercontent.com/5408195/73784021-90751b80-4749-11ea-9bdb-7a7210b26be3.png)

**Comment by StfBauer** [comment]
Then this issue is strange cause and the errors don't give any clue other then there was an issue with the network at some point.

```log
11037 silly extract error@7.2.1
11042 silly tarball trying error@^7.0.2 by hash: sha512-fo9HBvWnx3NGUKMvMwB/CBCMMrfEJgbDTVDEkPygA3Bdd3lM1OyCd+rbQ8BwnpF6GdVeOLDNmyL4N5Bg80ZvdA==
11164 silly extract error@^7.0.2 extracted to C:\Users\jv_65727\AppData\Roaming\npm\node_modules\.staging\error-9fc2d9d2 (1145ms)
11525 silly extract json-parse-better-errors@1.0.2
11532 silly tarball trying json-parse-better-errors@^1.0.1 by hash: sha512-mrqyZKfX5EhL7hvqcV6WG1yYjnjeuYDzDhhcAAUrq8Po85NBQBJP+ZDUT75qZQ98IkUoBqdkExkukOU7Ts2wrw==
11612 silly extract json-parse-better-errors@^1.0.1 extracted to C:\Users\jv_65727\AppData\Roaming\npm\node_modules\.staging\json-parse-better-errors-440c2474 (784ms)
11671 silly extract error-ex@1.3.2
11686 silly tarball trying error-ex@^1.2.0 by hash: sha512-7dFHNmqeFSEt2ZBsCriorKnn3Z2pj+fd9kmI6QoWw4//DL+icEBfc0U7qJCisqrTsKTjw4fNFy2pW9OqStD84g==
11763 silly extract error-ex@^1.2.0 extracted to C:\Users\jv_65727\AppData\Roaming\npm\node_modules\.staging\error-ex-cfb97b7f (437ms)
11810 silly extract create-error-class@3.0.2
11820 silly tarball trying create-error-class@^3.0.1 by hash: sha1-Br56vvlHo/FKMP1hBnHUAbyot7Y=
11877 silly extract create-error-class@^3.0.1 extracted to C:\Users\jv_65727\AppData\Roaming\npm\node_modules\.staging\create-error-class-6d977d7b (554ms)
12152 silly extract verror@1.10.0
12160 silly tarball trying verror@1.10.0 by hash: sha1-OhBcoXBTr1XW4nDB+CiGguGNpAA=
12222 warn tar ENOENT: no such file or directory, open 'C:\Users\jv_65727\AppData\Roaming\npm\node_modules\.staging\har-validator-4922f229\lib\error.js'
12244 silly extract verror@1.10.0 extracted to C:\Users\jv_65727\AppData\Roaming\npm\node_modules\.staging\verror-732ecd3c (2394ms)
12433 warn tar ENOENT: no such file or directory, open 'C:\Users\jv_65727\AppData\Roaming\npm\node_modules\.staging\rxjs-745a3f93\_esm2015\internal\util\canReportError.js'
12435 warn tar ENOENT: no such file or directory, open 'C:\Users\jv_65727\AppData\Roaming\npm\node_modules\.staging\rxjs-745a3f93\_esm5\internal\util\canReportError.js'
12438 warn tar ENOENT: no such file or directory, open 'C:\Users\jv_65727\AppData\Roaming\npm\node_modules\.staging\rxjs-745a3f93\internal\util\canReportError.js'
12444 warn tar ENOENT: no such file or directory, open 'C:\Users\jv_65727\AppData\Roaming\npm\node_modules\.staging\rxjs-745a3f93\_esm2015\internal\operators\catchError.js'
12445 warn tar ENOENT: no such file or directory, open 'C:\Users\jv_65727\AppData\Roaming\npm\node_modules\.staging\rxjs-745a3f93\_esm5\internal\operators\catchError.js'
12446 warn tar ENOENT: no such file or directory, open 'C:\Users\jv_65727\AppData\Roaming\npm\node_modules\.staging\rxjs-745a3f93\internal\operators\catchError.js'
12448 warn tar ENOENT: no such file or directory, open 'C:\Users\jv_65727\AppData\Roaming\npm\node_modules\.staging\rxjs-745a3f93\operators\catchError.js'
12729 verbose stack FetchError: request to https://github.com/pnp/vorpal/raw/master/vorpal-1.11.8.tgz failed, reason: self signed certificate in certificate chain
12729 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:392:9)
12729 verbose stack     at emitErrorNT (internal/streams/destroy.js:91:8)
12729 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
12735 error code SELF_SIGNED_CERT_IN_CHAIN
12736 error errno SELF_SIGNED_CERT_IN_CHAIN
12737 error request to https://github.com/pnp/vorpal/raw/master/vorpal-1.11.8.tgz failed, reason: self signed certificate in certificate chain

```

**Comment by vaderj** [comment]
On both systems, I ran everything in an Admin PowerShell console

**Comment by StfBauer** [comment]
What you could try to provide more details on your error would be to clone this repository and then try to `npm install` and `npm link` this project.

I might work but will give us some better insights on error, if you like to try this.

**Comment by vaderj** [comment]
git clone worked just fine but npm install went back to errors.

I did not attempt 'npm link'

[2020-02-04T21_05_59_806Z-debug.log](https://github.com/pnp/generator-spfx/files/4156090/2020-02-04T21_05_59_806Z-debug.log)


![image](https://user-images.githubusercontent.com/5408195/73787053-53ac2300-474f-11ea-842e-22a1928a123c.png)

**Comment by StfBauer** [comment]
@vaderj Thank you very much for trying this out helps a lot. Can you try to delete the package-lock.json in the root of the project and npm install again.

**Comment by vaderj** [comment]
[2020-02-04T21_39_56_712Z-debug.log](https://github.com/pnp/generator-spfx/files/4156298/2020-02-04T21_39_56_712Z-debug.log)

![image](https://user-images.githubusercontent.com/5408195/73789757-36c61e80-4754-11ea-8524-fe60796f55e4.png)

I also see this about halfway though the list of errors:
![image](https://user-images.githubusercontent.com/5408195/73789804-4e050c00-4754-11ea-87d3-6b48bdf2bc4f.png)

**Comment by StfBauer** [comment]
This whole issue comes from your .staging folder which is normally just temporary.

Can you please wipe the node_modules folder completely and delete the package-lock.json.

* npm install npm@latest -g
* npm cache clean  -- force

Some people issued similar issues about the .staggng - Most cases I found pointed to various issues. https://medium.com/@arunrajeevan/staging-npm-install-5d9fe8897b59

**Comment by vaderj** [comment]
After removing the contents in the /node_modules folder, update, and cache clearing, npm install still throws the same errors

![image](https://user-images.githubusercontent.com/5408195/73791629-8a863700-4757-11ea-81c9-91ba09662681.png)
[2020-02-04T22_02_47_746Z-debug.log](https://github.com/pnp/generator-spfx/files/4156390/2020-02-04T22_02_47_746Z-debug.log)


Also, I have 50GB free disk space on one server and 20GB free on my laptop

**Comment by vaderj** [comment]
Just to double check, I will try the same diagnostic on a VM at home in a few hours.  I could absolutely believe that my employer is blocking something as they like to block things first and ignore questions later

**Comment by StfBauer** [comment]
@vaderj thank you for your patience and understanding. Alternatively you could also try to use npx.

This allow you to one time run the generator. It would be interesting to see if this behaves differently.

```sh
npx -p yo -p @pnp/generator-spfx yo @pnp/spfx
```

**Comment by vaderj** [comment]
![image](https://user-images.githubusercontent.com/5408195/73793395-21082780-475b-11ea-8249-cadc1c1d660d.png)


[2020-02-04T22_29_16_179Z-debug.log](https://github.com/pnp/generator-spfx/files/4156452/2020-02-04T22_29_16_179Z-debug.log)

**Comment by StfBauer** [comment]
Thanks as it seems there is some self-signed certificate from Firewall / Proxy or whatever in the way. Curious of your outcome test at home. This is coming not from the generator itself.

**Comment by vaderj** [comment]
Sorry, I got distracted last night and I wasn't able to complete any testing

**Comment by StfBauer** [comment]
Any update from your side? @vaderj

**Comment by vaderj** [comment]
So its looking like its an issue with the corp network.  This morning, from home, I successfully got the PNP generator to create a solution.  

So this means theres some sort of network goofiness thats preventing some certificate from authenticating?

**Comment by StfBauer** [comment]
Yeah seems like that. If you are for example behind a proxy on your corporate network you need to configure that first.

It could also be that they do some sort of filtering.

This article might help you get setting it up: https://medium.com/@ogbemudiatimothy/using-npm-install-behind-a-corporate-proxy-server-db150c128899

**Comment by StfBauer** [comment]
Closed due inactivity.

**Comment by AjFromAz007** [comment]
I am having same issue, I cannot change the proxy settings. Would really appreciate any inputs, Thanks !
