### ISSUE TITLE
Error while generating a SP19 Vue Webpart

### ISSUE THREAD

**Issue by SkipperRG** [pnp/generator-spfx#230]
#### What Version you are running?
* NodeJS: 10.18.1
* NPM: 6.13.6
* @pnp/spfx: 1.11.0

#### Describe your problem

When i generate my first SP19 onwards Vue webpart with the generator and i want to start gulp serve, an error is displayed:

> Error - Unknown 
>  JSON validation failed:
> C:\Entwicklung\Testprojekt1\config\copy-assets.json
> 
> Error: #/ (Defines parameters for the task which...)
>        Expected type object but found type string

The file config/copy-assets.json looks like this:

> "{\n    \"$schema\": \"https://developer.microsoft.com/json-schemas/spfx-build/copy-assets.schema.json\",\n    \"deployCdnPath\": \"temp/deploy\",\n    \"extsToIgnore\": [\"vue\", \"d.ts\", \"d.ts.map\"]\n}\n"

When i correct the string to json, the error disappears:

> {
>     "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/copy-assets.schema.json",
>     "deployCdnPath": "temp/deploy",
>     "extsToIgnore": [
>         "vue",
>         "d.ts",
>         "d.ts.map"
>     ]
> }

**Comment by StfBauer** [comment]
This bug was fixed in version 1.11.1 - Thank you very much for pointing this out. Sadly like I mentioned in your other issue. VueJS has multiple problems with 1.4.1 or other words SharePoint 2019.
