### ISSUE TITLE
SPFx Angular elements: Unable to add a new web part to existing solution

### ISSUE THREAD

**Issue by gianespo** [pnp/generator-spfx#232]
#### General Information
* [x] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: v10.18.1
* NPM: 6.13.4
* @pnp/spfx: @pnp/generator-spfx@1.11.0

#### Describe your problem
When I try to add a new web part to an existing solution, the generator ask to replaces some configuration file (eg. config.json, package.json, etc.). I didn't seen the option to merge these.
Additionally in the Angular Element project the new web part component is not created and the web part in the -spfx project does not load an Angular component.
As result it is required extra effort to compare and modify files manually.

Following the steps used to add a new web part to an existing solution:
- cd <solution folder>
- yo @pnp/spfx
- answered wizard questions

**Comment by StfBauer** [comment]
@gianespo Which version of Angular have you used?

**Comment by gianespo** [comment]
@StfBauer I used the angular CLI version 8.3.5
Thanks

**Comment by StfBauer** [comment]
@gianespo Confirmed that is in deed a bug. What you could try meanwhile it to create a new web part using the regular SharePoint Framework. I should not behave differently.

**Comment by gianespo** [comment]
@StfBauer thanks for confirmed it. In any case I was able to add new the web parts by doing some stuff manually, for your reference following you can find where it is required to work on.

1. when the generator asks to replace some files the choses are:
- allow overwrite of config.json: this allow to view which changes are required, copy it and merge with the previous version.
- allow overwrite of package-solution.json: this replace the solution id, it should not be required but changing it does not have other impacts.
- do not overwrite all other files (package.json, readme.md, etc)

2. create with angular-cli the component for the new web part in the Angular project
3. change the ngDoBootstrap method in the app.module to define the custom element for the new webpart

4. manually modify the webpart.ts file in the -spfx project by:
- changing the render method by replacing the html content with the definition of the new custom element (see the first web part as sample)
- add the import for the bundle generated with the angular project
- review all other imports like in the first web part

Hope this could help also to identify where to fix the generator.
Thanks,
G.

**Comment by StfBauer** [comment]
@gianespo The re-run issue was a problem in the generator an should now be fixed. The problem was it was not detected that already a project has been generated.

This is now fixed.

There is still some wire up you have to do manually with a new web part in the same project because it would be pretty unwanted to overwrite your developed code.

If you have some ideas around this it would be great to hear. Think about this now for a long time.

**Comment by gianespo** [comment]
@StfBauer, thanks! Now this works. I understand the concerns about modify the Angular project where there is the developed code. However, the suggestions I can provide around this are:

- in the Angular project yous should be able to add a new component for the new web part, you could do this in the folder src/app/webparts folder as in the first creation phase. Then, if the user are moved away this, it was his choice and he will move also the new created component.

- in the app.module.ts you could add at the end of the ngDoBootstrap method the code to declare the new component as a custom element:
    const el3 = createCustomElement(YourWebPartComponent, { injector: this.injector });
    customElements.define('app-your-web-part', el3);
In this case you could use a random name for the element variable.

Hope this can be useful to improve the generator.
Thanks.

**Comment by gianespo** [comment]
@StfBauer, consider there is the same issue also when you try to add a List View extension to an existing project. The issue is not present if you add a Field customizer extension.
