### ISSUE TITLE
Why is Angular Elements (disabled) in options for framework selection ?

### ISSUE THREAD

**Issue by gonadn** [pnp/generator-spfx#238]
#### General Information
* [ *] Usage
* [* ] Development

#### What Version you are running?
* NodeJS: v10.16.0
* NPM: v6.13.7
* @pnp/spfx: 1.11.1 

![image](https://user-images.githubusercontent.com/3224441/74604063-93adc700-50ba-11ea-92a1-fa8d9a5c93cc.png)

**Comment by StfBauer** [comment]
@gonadn which version of Angular do you have installed? Have you yet upgraded to Angular 9? This version is currently not supported because of the multiple changes in the project setup.

**Comment by gonadn** [comment]
Hi StfBauer, i was developing anothe Angular web application, and i upgraded to Angular 9, without of thinking of it. Thanks., i fixed it by installing Angular 8.x v...
