### ISSUE TITLE
No Style using Angular Elements

### ISSUE THREAD

**Issue by Punisher612** [pnp/generator-spfx#240]
I tried to create a Webpart with Angular Elements, but the CSS Style did not load.
I had to add this line in the WebPart.ts file, to make it work:

`require('angular-elements/dist/AngularElements/styles.css');`

Is this a bug? Without this line I only have a  Webpart without Style.

**Comment by StfBauer** [comment]
If you like to use the style from the Angular Elements you can do it like this. If you like to style it in the Web Part you can use the CSS styles from the web part.

Two approaches and both are valid. The problem with styling in Angular Elements is that you cannot use the theming from SharePoint.

**Comment by StfBauer** [comment]
@Punisher612 Is the styling still an issue for you?

**Comment by Punisher612** [comment]
No, thanks.
I'm usinig the CSS Style from the Webpart now. In angular I use office-ui-fabric components with the help of microsoft/angualr-react, because my webpart should look like other Sharepoint webparts.
