### ISSUE TITLE
How to shows on IE11 for a package that scaffolded on Angular8 with pnp/generator-spfx

### ISSUE THREAD

**Issue by YijieWang-22** [pnp/generator-spfx#241]
■question
  IE11 doesn’t show a package that scaffolded on Angular8 with pnp/generator-spfx, but Edge and Chrome shows successfully.
  Please let us know how to shows on IE11

■Situation
　　Chrome shows [It works! Description: Hello world!] however IE11 shows nothing at the processes below.

■etails

　　▲Environment (Installed)
　　　・NodeJS LTS　　　          　　　　　　　　　10.19.0 Installed 
　　　・Yeoman and gulp 　　　　　　　　　　　　    Installed with command [npm install -g yo gulp]
　　　・generator-spfx @angular/cli        Installed with command [npm install -g @pnp/generator-spfx @angular/cli@8.3.25]

　　▲Processes
    ①Created a folder
    ②Run [yo @pnp/spfx]
　　　　　Default values selected but below
　　　　　　　? Choose your framework - Angular Elements (uses @angular/cli 8.3.25)
    ③Run a command below
　　　　　npm run bundle
    ④Moved to [-spfx] under the folder and run commands below
　　　　　　　gulp bundle --ship
　　　　　　　gulp package-solution --ship
    ⑤Uploaded the package into app catalog on sharepoint
    ⑥Created a new page on sharepoint and deployed the package
    ⑦can see the package with the page 6 by Chrome
    ⑧can’t see the package by IE11 as white out screen.

　　▲Complementary information 1
　　　　　after the process 3, run below
　　　　　　・npm run start
　　　　　　・Tried to see http://localhost:4200 by IE11 but doesn’t show [It works! Description: Hello world!]

　　▲Complementary information 2
　　　　　Verified that not fixed after tried to solve with below
　　　　　　・Moved to [src] under a folder (not [-spfx]) and validated comment below at [polyfills.ts] opened.
　　　　　　　import 'classlist.js';
　　　　　　　import 'web-animations-js';
　　　　　　・Run commands below
　　　　　　　npm install --save classlist.js
　　　　　　　npm install --save web-animations-js
　　　　　　　npm run bundle
　　　　　　　npm run start

**Comment by StfBauer** [comment]
IE 11 is currently not supported in the local workbench the only way is to test it online.

In case of Angular depending on the configuration several different polyfills can be included especially for the legacy IE 11.

You will find more information in their documentation: https://angular.io/guide/browser-support

Hope this helps.
