### ISSUE TITLE
[SPLoaderError.loadComponentError] IE11 shows the error message for a web-parts built by Angular7.

### ISSUE THREAD

**Issue by YijieWang-22** [pnp/generator-spfx#242]
InternetExplorer11 shows [SPLoaderError.loadComponentError] as we deploy on SPO site after Scaffolding using Angular with pnp/ generator-spfx.

We need your help how to solve.

Note: 

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment
Following an instruction above, we have done below.
    -	Install NodeJS (NodeJS LTS version 10)
    -	Install Yeoman and gulp
    -	Trusting the self-signed developer certificate

Processes we did: 
https://pnp.github.io/generator-spfx/howtos/angularelements/
ollowing an instruction above, we have done below.

    1.	npm install -g @pnp/generator-spfx @angular/cli@7.3.9
    2.	Command-Line Prompt activated
    3.	md <project-folder>
    4.	cd <project-folder>
    5.	yo @pnp/spfx
     (A)at [Choose your framework], we selected [Angular Elements (uses angular/cli 7.3.9)].  (Others are default value)
    6.	cd <angular-project-folder>
    7.	npm run bundle
    8.	cd ..\<spfx-project-folder>
    9.	gulp bundle --ship
   10.	gulp package-solurion --ship
   11.	Deployed the package on Application Catalog (app catalog) 
   12.	reated a page on SOP site and added the Web deployed.
   13.	Tried to show the page on IE11
     → SPLoaderError.loadComponentError (See the screen shot attached)
<img width="620" alt="Error" src="https://user-images.githubusercontent.com/61525968/75404110-eb66f080-594c-11ea-87d5-2907b6dab850.PNG">

**Comment by StfBauer** [comment]
Please see: https://github.com/pnp/generator-spfx/issues/241
