### ISSUE TITLE
Generating a bundle using angular elements takes 5 minutes

### ISSUE THREAD

**Issue by vvolodin** [pnp/generator-spfx#244]
I'm trying to embed my rather large Angular app using Angular Elements. My main.js is around 12 Mbytes uncompressed. When I'm importing the file in my WebPart (`import '../../client/main-es2015';`) it works but it seems like generating the web part bundle takes around 4-5 minutes. 
Is there a better way of importing my rather large compiled bundle?

**Comment by StfBauer** [comment]
Have you tried to keep it as an external reference and stored it on a CDN somewhere as you would do with any other library.

This way you won't have to bundle it in. In general, 12Mb is pretty huge, that may or may not the client needs to download. So you more like to make sure to load it from somewhere else anyway.

**Comment by vvolodin** [comment]
yes, I'd love to not put it through webpack again and I've tried to use config.json to define my files as external references but I couldn't find a way to import them properly in the web part's .ts file.

**Comment by StfBauer** [comment]
These are the steps you have to do IMO.

In the Angular Project edit the package.json:

```JSON
{
  "name": "ngprj",
  "version": "0.0.0",
  "main": "dist/<yourprojectname>/bundle",
  ...
}
```

Got now to your SharePoint config and add an external:

```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/config.2.0.schema.json",
  "version": "2.0",
  "bundles": {
    "hello-world-web-part": {
      "components": [
        {
          "entrypoint": "./lib/webparts/helloWorld/HelloWorldWebPart.js",
          "manifest": "./src/webparts/helloWorld/HelloWorldWebPart.manifest.json"
        }
      ]
    }
  },
  "externals": {
    "<YourAngularProjectName>": {
      "path": "https://<pathtoyourcdn/dist/ngprj/bundle",
      "globalName": "<your Angular project name>"
    }
  },
  "localizedResources": {
    "HelloWorldWebPartStrings": "lib/webparts/helloWorld/loc/{locale}.js"
  }
}
```

In the TypeScript file, you can now import it with the name of your project:

```typescript
import 'ngprj';
```

Instead of pointing to:

```typescript
import '<yourproject>/dist/bundle'
```

This way it should be treated like a [library component](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial) and don't bundle in anymore.

I haven't tried it out with Angular in particular but we use "regular libraries" instead of SPFx in the same way and it works. So the library won't be bundled in on production build and loads the library from the CDN instead.

Please let me know how this goes cause I might be smarter to adjust the scaffolding this way.

**Comment by StfBauer** [comment]
@vvolodin Were you able to get it running like a library component?

**Comment by vvolodin** [comment]
Yes, sort of! Thanks a lot.
I was able to compile my app into a single main.js bundle with polyfills in another js file. I've imported the main.js using `import 'appname'` syntax and it worked, but I couldn't load my polyfills package however I tried to use `import`. It also isn't clear how to include my extracted css.

Well, at least now I know it's possible to work with my huge bundle without waiting for 5 minutes for each reload.

**Comment by StfBauer** [comment]
@vvolodin Thank you for the update. So Angular uses webpack too and you could try to update the configuration for that using CSS Loader to create a bundle that also includes the CSS from your Angular component.

I created a custom scaffolding and library component setup that does exactly that.

Right now we just provide the general pattern how it could be used but there are more advanced scenarios that could be done. If you find something then please share.

**Comment by StfBauer** [comment]
Closed due inactivity.
