### ISSUE TITLE
Router outlet not triggering 

### ISSUE THREAD

**Issue by kamala93** [pnp/generator-spfx#247]
I am using angular elements framework to convert an application in angular to spfx, the default component if has router outlet alone is not getting triggered as in native angular code. Do we have to bootstrap it in any different manner rather than the ngDoBootstrap() that come along with the generator in app.module.ts?

**Comment by StfBauer** [comment]
Based on the information I found it seems like that Angular Elements do not support routing:
- https://github.com/angular/angular/issues/23740
- https://stackoverflow.com/questions/50990501/angular-elements-router-outlet

In general Angular Elements are more like web components that you just put on a page and work as stand-alone web controls.

**Comment by kamala93** [comment]
Thanks for your response. But actually I am facing the issue only when using the generator. I have the router outlet loading all the components one by one with ng serve command given in the angular code, but the spfx folder generated with pnp generator does not trigger the router outlet with gulp serve. 
Also please let me know why the app. component.ts and app.component.html is not present in the package generated with the pnp-spfx generator?
Also can we give bootstrap instead of entrycomponents in the ap.module.ts for routing to work?
Let me know if you need additional info to get an idea on this issue I have been facing.
