### ISSUE TITLE
APP available on all sites and subsites

### ISSUE THREAD

**Issue by vinaunder** [pnp/generator-spfx#248]
#### General Information
* [x ] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

i have a webaplicattion. with a main site and some subsites. on my parent site I have my appCatalog, with my apps installed.
if i add the apps on the main site, when i go to a subsite i can't add the app, since it is already being used.
Is there any way I can add it to the parent site and be available for all sites?

**Comment by StfBauer** [comment]
Can you please open this question in the general SPFx issue list on [sp-dev-doc](https://github.com/SharePoint/sp-dev-docs).

Thank you.
