### ISSUE TITLE
New Feature Request: Sync package.json version with package-solution.json

### ISSUE THREAD

**Issue by hugoabernier** [pnp/generator-spfx#250]
#### General Information
* [ ] Usage
* [ ] Development
* [ ] Documentation
* [x] Feature Request

#### Specific generator
* [x] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: v8.16.0
* NPM: 6.4.1
* @pnp/spfx: 1.12.0

#### Describe your problem
It would be great to use something similar to [Stefan Bauer's gulp task](https://n8d.at/how-to-version-new-sharepoint-framework-projects/) to synchronize the `package.json` version with `package-solution.json`.

This would help encourage using `npm version` to version solutions with more rigor, and might help with a wider adoption of a proper [semantic versioning schema](https://semver.org/).

Plus, @sympmarc  wants it.

I'd be happy to contribute to this feature, but my bet is that @StfBauer probably has something in his bag of tricks he could leverage.

**Comment by StfBauer** [comment]
Ohh this is already there for a long time. I thought you meant the thing with printing it in the web part.

**Comment by heinrich-ulbricht** [comment]
@StfBauer This issue comes up top when searching for how to synchronize package-solution.json with package.json. Could you maybe add a quick hint or link on how to configure this?

Search results contain lots of complicated solutions that might be outdated. Was it as easy as setting the version to '*'?

**Comment by StfBauer** [comment]
The same as it always was.
