### ISSUE TITLE
Router outlet not triggering with ngdobootstrap

### ISSUE THREAD

**Issue by kamala93** [pnp/generator-spfx#251]
Issue 247 contd.
Thanks for your response and sorry for the delay.
But actually I am facing the issue only when using the generator. I have the router outlet loading all the components one by one with ng serve command given in the angular code, but the spfx folder generated with pnp generator does not trigger the router outlet with gulp serve.
Also please let me know why the app. component.ts and app.component.html is not present in the package generated with the pnp-spfx generator?
Also can we give bootstrap instead of entrycomponents in the ap.module.ts for routing to work?
Let me know if you need additional info to get an idea on this issue I have been facing.

**Comment by StfBauer** [comment]
Like I already mentioned in the previous issue only the limited scope of Angular Elements could be used, which are comparable to some web components.
My nature this components have limited capability. If you found better approaches please share and we can add them to the generator.

Thank you.

**Comment by kamala93** [comment]
Thanks so much. The generator was useful for single page components without much routing activity anyways.

**Comment by StfBauer** [comment]
Closed due inactivity.
