### ISSUE TITLE
Can't create app customizer

### ISSUE THREAD

**Issue by stact** [pnp/generator-spfx#252]
#### General Information
* [ ] Usage
* [x ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: v12.13.0
* NPM: 6.14.2
* @pnp/spfx: 1.12.0

I've created a webpart with generato, no issue, but to create app customizer, it seems something is missing. 

Here the configuration:
![image](https://user-images.githubusercontent.com/9899166/78757689-32e59100-797d-11ea-9269-27f304a65970.png)

```
Error: ENOENT: no such file or directory, scandir '/home/superadmin/.config/yarn/global/node_modules/@microsoft/generator-sharepoint/lib/generators/onPrem19ApplicationCustomizer/templates/react'
```

Let me know if you need further information

**Comment by stact** [comment]
oh really, I forgot to install yo microsoft generator. (it's a fresh install, maybe prerequisites is missing on documentation?) or improve yarn global add @pnp/generator-spfx to include @microsoft/generator-sharepoint?

**Comment by stact** [comment]
Still the same problem even with including @microsoft/generator-sharepoint

**Comment by StfBauer** [comment]
@stact Sorry for the inconvenience but only web parts, as far as I know, are supported on on-premises.
https://github.com/SharePoint/sp-dev-docs/issues/3590

We will remove this option on the next release of the generator.

**Comment by stact** [comment]
Duly noted. I'm using standard spfx generator and it's working. I'm tired to work with on premise version xD only specifics workaround (Microsoft no more onpremise versions)
