### ISSUE TITLE
Not able to include external scss files 

### ISSUE THREAD

**Issue by kamala93** [pnp/generator-spfx#254]
I am trying to create a solution with angular elements with the generator. I am using a global sass file named styles.scss in addition to the sass files in corresponding components.I have added it in the angular.json file of the angular folder generated. I try the following to include in the spfx webpart.ts:
I have few @import statements in the styles.scss file
require('angular/src/styles.scss')

But i get the following error.

_Module parse failed: Unexpected character @ 
You may need an appropriate loader to handle this file type. Currently no loaders are configured to process this file.
|
@import 'variables'
@import '../node_modules/bootstrap/scss/bootstrap'
|

Can you please guide me on how to add external sass file in the solution with angular elements.

**Comment by StfBauer** [comment]
Do you get this message in the Angular or in the SPFx project?

**Comment by kamala93** [comment]
I am getting this error in the spfx folder when I give gulp bundle command. It renders fine in the angular folder when bundled with npm run bundle.

I had given the following in the webpart.ts file to include the sass from the angular folder.

require('angular/src/styles.scss')

**Comment by StfBauer** [comment]
Have you checked if Angular Elements bundled the CSS in? otherwise, you can load the CSS directly from the angular project into SPFx.

**Comment by kamala93** [comment]
I did check the angular bundled dist folder and the css when imported works fine. Thanks for that.
But why is the spfx folder throwing error for the @import in sass files when imported?
I actually have even added sass package in the spfx folder with npm install.

**Comment by StfBauer** [comment]
Any chance to share your project? or a stripped-down version that use the same methods you use in your project.

This way it would easier to see your issue.

**Comment by kamala93** [comment]
Sorry, will not be able to share the code exactly , but will give you a sample version of new project with the issue replicated.

**Comment by chandaniprajapati** [comment]
To include external styles in angular element and use styles of this angular element in spfx webpart.

Follow below steps :
For example I want to include `bootstrap` css from  `node_modules/bootstrap/dist/css/bootstrap.min.css`.

Then we need to add this path in `angular.json` as shown below,

```
{
    "..."
    "projects": {
      "angulartest": {
          "..."
          "build": {
            ...
            "styles": [
                "node_modues/boostrap/dist/css/bootstrap.min.css",
                "src/styles.scss"
              ],
            },
      }
    }
}
  
```
 
now when we build angular-element project using `npm run bundle`, it will have two files `bundle.js` and `styles.css`.

To use this styles file in spfx-webpart, include it in `spfx-webpart.ts` as below
```js
require('../../../node_modules/[angularSolutionNameKebabCase]/dist/[angularsolutionname]/styles.css');

```

**Comment by StfBauer** [comment]
Thanks to @chandaniprajapati this should now be possible.
