### ISSUE TITLE
Lock file's @types/react@16.8.8 does not satisfy @types/react@^16.9.17

### ISSUE THREAD

**Issue by Ted-Lalakas** [pnp/generator-spfx#255]
#### General Information
* [ ] Usage
* [ ] Development
* [ ] Documentation
* [ x ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: 10.17.0
* NPM: 6.11.3
* @pnp/spfx: 1.12.0

I created a new SPFx solution using "yo @pnp/spfx" using settings:

Sharepoint Online
ReactJS

**Libraries to Include: pnpjs, and Office UI Fabric**
UI Fabric: Default 6.x.x
Typescript v3.3 (default)

**Vetting options:** WebPack Bundle Analyzer, Style Linter
**Pipelines:** Azure DevOps Multi-Stage Pipeline with deployment.
Jest

---------------------------------------------------------------------------
After that I added a simple jest test (some addition task to pass just for testing purposes) One thing I found using "gulp test" was that I wasn't receiving the output of the test but either way that's not the issue.

I deployed this repo to Azure DevOps with no extra components or any changes in code whatsoever. I simply wanted to test Pipelines and see that everything worked out of the box.

When running the pipeline I receive in the "npm ci" section that:
npm ERR! 
npm ERR! 
npm ERR! Invalid: lock file's @types/react@16.8.8 does not satisfy @types/react@^16.9.17
npm ERR! 

Looking at the package.json file generated I see that in dependencies and devDependencies the versions of @types/react are different:
"@types/react": "16.8.8"
"@types/react": "^16.9.17"

Fixing this problem is not an issue on my end. I was able to manually sync the versions and the npm ci process completed with no errors, however, I feel as if this issue should not exist from a new project out of the box and require manual intervention.

I have attached some screenshots. I hope this helps.
![error1](https://user-images.githubusercontent.com/17604777/79825221-d0a87980-83db-11ea-98a9-b8e9307324b8.png)
![error2](https://user-images.githubusercontent.com/17604777/79825235-d69e5a80-83db-11ea-9b2a-acf05610c02b.png)

**Comment by StfBauer** [comment]
@Ted-Lalakas the solution is to remove the "@types/react": "^16.9.17" this was smuggled in via the Office UI Fabric addition.

After you removed it from the package.json - delete the package-lock.json and npm install.

The issue will be fixed on next release.

**Comment by Ted-Lalakas** [comment]
Thank you @StfBauer.
