### ISSUE TITLE
Extra characters in config.json

### ISSUE THREAD

**Issue by kcraigo** [pnp/generator-spfx#257]
#### General Information
* [ ] Usage
* [X] Development
* [ ] Documentation
* [ ] Feature Request

**Issue:** 
Latest version of generator-spfx is generating extra characters
}.js"
  }
}

**Result:** 
 config/config.json: Unexpected token '.' at 19:2
}}.js"
  }

**Fix:**
Remove 
}}.js" 
 }

**Steps to repeat:**
Create a new solution
yo @pnp/spfx

**Comment by StfBauer** [comment]
@kcraigo thank you. Can you please add some more detail what settings you have taken after you ran yo @pnp/spfx? Thank you.

**Comment by kcraigo** [comment]
@StfBauer I've updated to the latest and greatest yeoman and @pnp/spfx, created a new project and this is no longer an issue. Thank you!

**Comment by StfBauer** [comment]
Thank you for the update @kcraigo
