### ISSUE TITLE
Found Angular Elements disabled in latest version (1.13.0)

### ISSUE THREAD

**Issue by chandaniprajapati** [pnp/generator-spfx#261]
#### General Information
* [ ] Usage
* [x] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS:  10.13.0
* NPM: 6.4.1
* @pnp/spfx: 1.13.0
* @angular/cli: 9.0.7 

Getting Angular Elements disabled for the above-mentioned version. please find the screenshot below.
![pnp generator](https://user-images.githubusercontent.com/52065929/82721523-608f5b00-9cdb-11ea-9c47-371b3ddaba41.png)

**Comment by StfBauer** [comment]
Angular 9 is currently not supported yet.
