### ISSUE TITLE
Not able to add new component

### ISSUE THREAD

**Issue by gauravgoyal5** [pnp/generator-spfx#263]
#### General Information
* [X] Usage
* [X] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] No Framework

#### What Version you are running?
* NodeJS: 10.18.1
* NPM:6.13.4
* @pnp/spfx: 1.13.0

#### Describe your problem
I am able to create new SPFx project but when I am trying to add more component with yo @pnp/spfx, breaking with message  "!!! Project needs to be upgraded !!!
> Please review the file  upgrade-log.md  in the project root."

![image](https://user-images.githubusercontent.com/6926513/83254711-dd836e80-a1cc-11ea-9303-1314fc86c330.png)

**Comment by StfBauer** [comment]
@gauravgoyal5 Can you post your .yo-rc file here?

**Comment by StfBauer** [comment]
Fixed in version 1.13.1.
