### ISSUE TITLE
Not able create library component.

### ISSUE THREAD

**Issue by gauravgoyal5** [pnp/generator-spfx#265]
#### General Information
* [X] Usage
* [X] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [X] React
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: v10.18.1
* NPM: v6.13.4
* @pnp/spfx: 1.13.0

#### Describe your problem
Not able to generate library component with React JS. It is throwing error & not generating any thing.
![image](https://user-images.githubusercontent.com/6926513/83405102-7282a380-a429-11ea-8a72-d55cbf660b1a.png)

**Comment by StfBauer** [comment]
Please see issue #195 - Library components do not support ReactJS.
