### ISSUE TITLE
Generator does not respect solution/component naming arguments

### ISSUE THREAD

**Issue by joshtransient** [pnp/generator-spfx#268]
#### General Information
* [X] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: 10.20.1
* NPM: 6.14.4
* @pnp/spfx: 1.14.1

Sample command: `yo @pnp/spfx --solution-name "NewSolution1" --component-name "NewSolution1" --component-description "New Solution web part" --skip-install`

Expected behavior: generator doesn't ask for the solution name, or name or description of the new component

Actual behavior: generator asks for the solution name, and name and description of the new component

Some arguments are still respected, namely `--skip-install` in this example.

**Comment by StfBauer** [comment]
Thank you @joshtransient - I can confirm this is a bug.

**Comment by StfBauer** [comment]
The issue got fixed in version 1.14.2 - Thank you for letting us know.
