### ISSUE TITLE
Access to component type info

### ISSUE THREAD

**Issue by joelfmrodrigues** [pnp/generator-spfx#277]
#### General Information
* [ ] Usage
* [x] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [x] Addons
* [ ] HandlebarsJS

Hi, 
In code, how can I access the type of component that was selected? (webpart, extension, library)
Is this even exposed together with properties like skip-install for instance? Tried all sorts of things and can only get undefined results.

Thanks

**Comment by StfBauer** [comment]
You can't. At maximum, you get the latest version via .yo-rc.json.

**Comment by joelfmrodrigues** [comment]
Thanks, I will need to re-think my options :)
Closing...

**Comment by StfBauer** [comment]
Yeah sadly this issue also infects other features of the generator.
