### ISSUE TITLE
Error on Package Deployment on SharePoint Online Site Page -> Cannot access 'e' before initialization

### ISSUE THREAD

**Issue by sagar4u** [pnp/generator-spfx#279]
#### General Information
* [- ] Usage
* [-] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS
* [-] Angular Element

**What Version you are running?**
**NodeJS**: v10.13
**NPM**: v6.4.1
**@pnp/spfx**: 2.0.10.
**@pnp/generator-spfx**@1.15.0

**Describe your problem**
I am working on SPFX with Angular Elements generated using 'pnp/generator-spfx'. The entire application runs perfectly when I use 'gulp serve' and run it from 'https://localhost:4321/' server whether I test it on Hosted workbench or local workbench. All works fine.

However, when I actually prepare the SPFX solution package using following commands. Commands are run in following order:-
1. gulp clean
2. gulp build --ship
3. gulp bundle --ship
4. gulp package-solution --ship

The package is created successfully and also is deployed. When a webpart is added on modern page, it throws the error while rendering in the console.
"

> Cannot access 'e' before initialization

"
Below is the screenshot of the console.
![image](https://user-images.githubusercontent.com/18418691/94032284-6b6b1100-fddd-11ea-8208-db45f221386b.png)

Any help is appreciated. Thank you in advance.

Thanks,
Sagar

**Comment by sagar4u** [comment]
Further troubleshooting tells me that when I run following commands on spfx project
gulp clean; gulp serve;

The workbench renders the angular components properly without any error.

However, when I use '--ship' in the command, the above error starts coming and components are not loaded properly
gulp serve --ship
It throws the same error shown in the screenshot cannot acces e before initiallization'

This makes me wonder project is not building properly when I use '--ship' in the command.

**Comment by StfBauer** [comment]
Can you please share your sample project. This way it is easier to troubleshoot. Thank you.

**Comment by sagar4u** [comment]
@StfBauer , Thank you for the response. The error is coming for the generated scaffolded project without any changes. Please find the attached solution (zip) as requested. Thanks again.
[TestAngularElements.zip](https://github.com/pnp/generator-spfx/files/5284460/TestAngularElements.zip)

**Comment by sagar4u** [comment]
Just to confirm again that the error is coming for the scaffolded project and not by any changes later, I tested today and faced same issue. To get this error, we don't need a deployment but simple 'gulp serve --ship' suffice to reproduce the errors and blocks angular components completely.

Steps to reproduce:
1. Create a brand new project using the commands
=> npm install -g @pnp/generator-spfx @angular/cli
=> yo @pnp/spfx
2. Select a webpart with angular element as an option
3. Once all is done, run 'npm install' on angular project and for spfx project to install all dependencies
4. Go to Angular elements project and run 'npm run bundle' command
5. Go to SPFX project and run 'gulp serve --ship' command to open the workbench (local/hosted)
6. Add a wepbart to the page.

On developer console, you'll notice these errors and angular components are not loaded/rendered.

**Comment by chandaniprajapati** [comment]
Hi @sagar4u,

I have analyzed this issue. This issue is might be occurred because of the over minification of angular elements `bundle.js`, When we generate an angular element application build it minify the app and then we combine it in `bundle.js`. Now when we serve the production build of the web part with `gulp serve --ship` it again minifies the already minified bundle. which creates an issue.

To fix this build angular element build with `--optimization=false`. for this update script in `angular-element-app/package.json` as below 

```
    "bundle": "ng build --prod --output-hashing none --optimization=false && node elements-build.js"
```

Now you can serve production build with `gulp serve --ship` and test and also make a package and test, it will work.

Let me know if you have any doubts :)

**Comment by sagar4u** [comment]
@chandaniprajapati, yes you're right... This solution is solving the error and angular components are working on the page. I tried it using 'gulp serve --ship' command which is working now. Thank you.

**Comment by sagar4u** [comment]
@chandaniprajapati I closed the issue, however is it possible for you to submit this change in 'generator-spfx' code. This is really required change for Angular Elements to work in SPFX.
