### ISSUE TITLE
Unable to load Angular WebPart in local workbench on Edge 42

### ISSUE THREAD

**Issue by Tokelin** [pnp/generator-spfx#285]
#### General Information
* [X] Usage

#### What Version you are running?
* NodeJS: 10.23.0
* NPM: 6.14.8
* @pnp/spfx: 1.15.1
* Angular CLI: 10.2.0
* Edge: 42.17134.1.0

#### Describe your problem
When using the [@pnp/spfx](https://pnp.github.io/generator-spfx/howtos/angularelements/) generator and generate a simple HelloWorld project the Angular WebPart is unable to load when using `gulp serve` in Edge 42.17134.1.0

#### Steps to reproduce

1. Follow instructions on the [@pnp/spfx](https://pnp.github.io/generator-spfx/howtos/angularelements/) page for generating an Angular SPFX solution
1. Run `gulp serve`
1. When the local workbench loads, press the '+' to add the Angular WebPart
1. The WebPart doesn't load and there are two errors in the console: 
```
[1605706764928][OtherGlobalError.window.onerro] Error: Error:[object ErrorEvent], file:undefined, line:undefined, column:undefined
TypeError: Function expected
```

#### Additional context

I have tested the generated solution in Firefox and Chrome and the error is not present. Also I have generated a new project using Vue.js and the WebPart is being displayed correctly

**Comment by StfBauer** [comment]
You mention in your issue that uses used Edge 42. This browser never existed. Only Google Chrome 42 exists.

<img width="325" alt="image" src="https://user-images.githubusercontent.com/5503835/99843659-33c8dd00-2b72-11eb-99d2-c638be3007c1.png">

The first Chromium-based Edge version was 80:
<img width="132" alt="image" src="https://user-images.githubusercontent.com/5503835/99843758-56f38c80-2b72-11eb-9569-33fa9abac023.png">

So it is hard to test against a browser that never existed. I tested it anyway in Chrome 42 and got the following error:

<img width="946" alt="image" src="https://user-images.githubusercontent.com/5503835/99844973-34fb0980-2b74-11eb-9e09-bedc53466b0c.png">

Please tell me which browser you test in?

@Tokelin Can you please share your solution/base project? This makes it easier to reproduce your issue.

In all current Edge and Chrome version, the web part loaded without any problem.

**Comment by Tokelin** [comment]
I am testing in Microsoft Edge 42.17134.1.0 which uses Microsoft EdgeHTML 17.17134
![image](https://user-images.githubusercontent.com/67515444/100086212-c5c43480-2e55-11eb-96dc-cefe43af4d85.png)

The base project I am using is a solution generated with `yo @pnp/spfx` and using default options.

![edge](https://user-images.githubusercontent.com/67515444/100087174-fce71580-2e56-11eb-8a50-3dcd7cf1228e.png)

This is what I see after adding the HelloWorld webpart.

**Comment by StfBauer** [comment]
Ok, that makes sense now, but it is a beta version of Microsoft Edge, and I assume that on one at the Angular Team has ever tested it with this version probably.
Found a similar issue from October 2019: https://github.com/angular/angular/issues/33031

I will check your solution with the most current Edge browser, and see if it works in the current browser version, these are also the only version that will be supported by Microsoft 365 in the future.

The first officially Chromium-based Edge version was, release 15th January 2020.
https://support.microsoft.com/en-us/microsoft-edge/download-the-new-microsoft-edge-based-on-chromium-0f4a3dd7-55df-60f5-739f-00010dba52cf

This version was already: Edge 79

Please upgrade to a newer stable version: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel
