### ISSUE TITLE
SPFx Webpart With Angular Elements not working in SharePoint page 

### ISSUE THREAD

**Issue by BhattMeet98** [pnp/generator-spfx#293]
Hello Everyone,

I have created a demo of [SPFx Webpart With Angular Elements](https://www.c-sharpcorner.com/article/spfx-with-angular-elements/) with reference to this link.

I have successfully bundle that project and serve that project with "npm run bundle" and "gulp serve" commands.

It is running correctly in workbench / local.  Please refer to below screenshot,
![SS](https://user-images.githubusercontent.com/81350109/113578865-1be58780-9641-11eb-8f86-0d30a03215e8.png)

When I have published that solution using "gulp bundle --ship" and "gulp package-solution --ship" commands. .sppkg file has been generated successfully. But when I add that app to my SharePoint page it throws a below error,
![SSS](https://user-images.githubusercontent.com/81350109/113578898-29027680-9641-11eb-88d8-f5d2b64423fe.png)

If anyone has an idea for the same. Please let me know.

Thanks in Advance.

**Comment by chandaniprajapati** [comment]
Hi @BhattMeet98, thanks for reporting an issue. will check and let you know. 
Can you please tell me which version you are using for PNP-generator-spfx and angular elements?

**Comment by BhattMeet98** [comment]
Hi, @chandaniprajapati thanks for your quick response. 

I am using below version for PNP-generator-spfx
+-- @angular/cli@11.1.2
+-- @microsoft/generator-sharepoint@1.11.0
+-- @pnp/generator-spfx@1.16.1
+-- gulp@4.0.2
`-- yo@3.1.1

I am using the below version for angular elements
"@angular/elements": "^11.1.2"

Please let me know if you need more feedback from my side.

Thanks

**Comment by chandaniprajapati** [comment]
Hi @BhattMeet98, I have created a sample and deployed it and it's working fine. I am not able to reproduce an issue. 
Can you please share the source code if possible?
Thanks :)

**Comment by BhattMeet98** [comment]
HI, @chandaniprajapati 
Sorry for the late response,

I have clone code from the below link,
https://github.com/chandaniprajapati/spfx-angular-elements

opened "AngularElements" folder in VS code terminal and run npm run bundle then 

opened "AngularElements-spfx" folder in VS code terminal and run gulp bundle --ship and gulp package-solution --ship

**Comment by chandaniprajapati** [comment]
Hi @BhattMeet98,

Sorry but I am not able to reproduce an issue.

The step which I have followed:

- Clone the repo.
- Then move to the angular folder and run `npm i` and `npm i bootstrap`
- Then I moved to the spfx folder and install `npm i`
- Moved to the angular folder and run `npm run bundle`
- then moved to the spfx webpart and run `gulp bundle --ship` and `gulp package-solution --ship`.
- Then added a package to the app catalog and install its site and added to the page.

Thanks :)

**Comment by BhattMeet98** [comment]
Hi @chandaniprajapati ,

I have tried steps as you have suggested,

Now, I got an error while executed "gulp bundle --ship" command. Please refer to the below screenshot for the same,

![SS](https://user-images.githubusercontent.com/81350109/113821787-341cea00-979a-11eb-9c5b-3278fb3d94fb.png)

Unexpected results we have shown from last 2 days :(

**Comment by chandaniprajapati** [comment]
Hi @BhattMeet98 ,

Have you run command `npm i` in `AngularElements-spfx` ?

Thanks.

**Comment by BhattMeet98** [comment]
Hi @chandaniprajapati,

Thanks for quick response,

I have successfully performed the below steps,

1. Clone the repo.
2. Then move to the angular folder and run npm i and npm i bootstrap
3. Then I moved to the spfx folder and install npm i
4. Moved to the angular folder and run npm run bundle

**Comment by chandaniprajapati** [comment]
Hi @BhattMeet98 ,

Is it working correctly now?

Thanks.

**Comment by BhattMeet98** [comment]
Hi @chandaniprajapati 

I am unable to execute below commands

1. then moved to the spfx webpart and run gulp bundle --ship and gulp package-solution --ship.
2. Then added a package to the app catalog and install its site and added to the page.

**Comment by BhattMeet98** [comment]
Hi @chandaniprajapati ,

I have git clone from below repository,
https://github.com/phawrylak/spfx-angular-elements

After that perform the below steps,
1. Then move to the angular folder and run npm i and npm i bootstrap
2. Then I moved to the spfx folder and install npm i
3. Moved to the angular folder and run npm run bundle
4. then moved to the spfx webpart and run gulp bundle --ship and gulp package-solution --ship.
5. Then added a package to the app catalog and install its site and added to the page

I stuck at 3 step npm run bundle. Please refer below screenshot,

![SS](https://user-images.githubusercontent.com/81350109/113829530-3a639400-97a3-11eb-802b-65534830a1f0.png)

Hope we found a better way.

**Comment by BhattMeet98** [comment]
Hi @chandaniprajapati ,

I have tried to create a demo using the below link,
https://sharepointcorner.tech/spfx-webpart-with-angular-elements/

But sill faced the same issue :(

**Comment by BhattMeet98** [comment]
Hi @chandaniprajapati ,

I have tried to create a demo using the below link,
https://github.com/Amos-MSFT/SharePoint-FrameWork-Demos/tree/master/SPFxAngular9-master

But still not working correctly. Please refer below screenshot
,
![SS](https://user-images.githubusercontent.com/81350109/113854896-085f2b80-97bd-11eb-8564-06f01f2b9a6d.png)

**Comment by chandaniprajapati** [comment]
Hi @BhattMeet98, I will suggest you create a sample app from scratch and check whether it is working or not bcoz I am not facing any type of an issue so I am not able to found it.

Thanks :)

**Comment by BhattMeet98** [comment]
Hi @chandaniprajapati I have created an app from scrap as per suggestion in the below link,
https://sharepointcorner.tech/spfx-webpart-with-angular-elements/

But it's not working correctly.

Thanks :)

**Comment by BhattMeet98** [comment]
Hi @chandaniprajapati,

I have created a demo as you have suggested

- Created a sample app from scratch. 
- Move to the angular folder. 
- Run "npm run bundle" command

I got an error while running the "npm run bundle" command. Please refer to the below screenshot,

![SS](https://user-images.githubusercontent.com/81350109/113861011-5af01600-97c4-11eb-9c2e-736642369f1e.png)

Once the above issue is resolved I will move to the spfx webpart and run "gulp bundle --ship" and "gulp package-solution --ship" commands.

**Comment by BhattMeet98** [comment]
> Hi @BhattMeet98, I have created a sample and deployed it and it's working fine. I am not able to reproduce an issue.
> Can you please share the source code if possible?
> Thanks :)
I have added my code in git. Please refer my git repo link.
https://github.com/BhattMeet98/angular-element-sample-project

**Comment by BhattMeet98** [comment]
Hi @chandaniprajapati,
Can you please tell me which version you are using for PNP-generator-spfx and angular elements?
I will install the same versions and try to create a new project.

**Comment by chandaniprajapati** [comment]
Hi @BhattMeet98,

Please check the below image and ignore the errror.

![image](https://user-images.githubusercontent.com/52065929/113970747-08126f00-9855-11eb-8ef6-f4ede1c85c92.png)

Thanks :)

**Comment by BhattMeet98** [comment]
Hi @chandaniprajapati ,

I have installed the same versions.

![SS](https://user-images.githubusercontent.com/81350109/114001021-2f7b3300-9879-11eb-8f73-911f307780bd.png)

Git clone from below repo,
https://github.com/chandaniprajapati/spfx-angular-elements

After that perform the below steps,

1. move to the angular folder and run npm i and npm i bootstrap
2. moved to the spfx folder and install npm i
3. moved to the angular folder and run npm run bundle
4. moved to the spfx webpart and run gulp bundle --ship and gulp package-solution --ship.

Below error occurs while run gulp bundle --ship

![SS2](https://user-images.githubusercontent.com/81350109/114013290-fc3ea100-9884-11eb-9c7d-563c0f6f7746.png)

Have you any idea about that error?

**Comment by chandaniprajapati** [comment]
Hi @StfBauer, Can you help to @BhattMeet98 with this issue?

Thanks :)

**Comment by chandaniprajapati** [comment]
Hi @BhattMeet98,
 
Can you please refer to this https://sharepoint.stackexchange.com/questions/191289/gulp-serve-error-cannot-find-module-microsoft-sp-build-web. may it solve your issue.

Thanks

**Comment by BhattMeet98** [comment]
Hi @chandaniprajapati,

I have clone code from blow repo,
https://github.com/phawrylak/spfx-angular-elements

After that perform the below steps,

1. moved to the angular folder and run npm i and npm i bootstrap
2. moved to the spfx folder and install npm i
3. moved to the angular folder and run npm run bundle
4. moved to the spfx webpart and run gulp bundle --ship and gulp package-solution --ship.

Kindly check the below links if you get an error,
https://github.com/phawrylak/spfx-angular-elements/issues?q=is%3Aissue+is%3Aclosed

It successfully bundles the sppkg file and I have added it on my SharePoint page and it is working correctly.

![SS](https://user-images.githubusercontent.com/81350109/114025922-4c246480-9893-11eb-823c-87ea08f91733.png)

If you have any idea about the below change, please let me know for the same,
https://github.com/phawrylak/spfx-angular-elements/issues?q=is%3Aopen+is%3Aissue

Thanks :)

**Comment by BhattMeet98** [comment]
Hi @chandaniprajapati,

I need to perform CRUD operation with SharePoint list with spfx-angular-elements.
Can you please help me with the same?

Thanks in Advance :)

**Comment by chandaniprajapati** [comment]
Hi @BhattMeet98,

You can refer to this link https://sharepointcorner.tech/spfx-webpart-with-angular-elements/ 

In which I have already implemented CRUD operations with the ToDo list.

May this helps to you.

Thanks :)

**Comment by BhattMeet98** [comment]
Hi @chandaniprajapati 

Thanks for the quick response.

I will create a demo with reference to that link.

I will let you know if any issue.

Thanks :)

**Comment by StfBauer** [comment]
Besides @chandaniprajapati great post on how she implemented a ToDo-List there are also several other good blog posts around for example like this one:
https://gonadn.medium.com/spfx-with-angular-element-crud-operations-using-pnpjs-5a8a18ed6e43

The purpose of this issue list is to document issues with the generator but not on actually implementing things with a specific technology. Thank you.

**Comment by BhattMeet98** [comment]
Hi @StfBauer and @chandaniprajapati 

I have created a demo with reference to the below link,
https://gonadn.medium.com/spfx-with-angular-element-crud-operations-using-pnpjs-5a8a18ed6e43

It is working correctly in the workbench. Kindly refer to the below image,

![SS2](https://user-images.githubusercontent.com/81350109/114144402-eb4c6900-9932-11eb-945d-915421fe9059.png)

It is not working correctly on the SharePoint page. Kindly refer to the below image,

![SS](https://user-images.githubusercontent.com/81350109/114144564-18008080-9933-11eb-9cdb-8c48d59767c7.png)

Can you please assist me with the same?

Thanks :)

**Comment by StfBauer** [comment]
You need to debug your rest API something there is wrong preferably using a tool like postman or other browser tool.

https://anoopt.medium.com/accessing-sharepoint-data-using-postman-sharepoint-rest-api-76b70630bcbf
