### ISSUE TITLE
SPFX Generator for 2019 on premise

### ISSUE THREAD

**Issue by Link631** [pnp/generator-spfx#295]
#### General Information
* [ ] Usage
* [x ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: 8.17.0 
* NPM: 4.6.1
* @pnp/spfx: 

Hi everyone,

I want to setup a SharePoint Framework project for SharePoint 2019 on premise.

From the microsoft docs, i find this version prerequisites:
![Capture1](https://user-images.githubusercontent.com/54800010/116774442-e2941200-aa5c-11eb-9aab-56657ffab78b.PNG)

For spfx 1.4.1 following dependency is listed:
![Capture2](https://user-images.githubusercontent.com/54800010/116774488-24bd5380-aa5d-11eb-9c1a-e3877f57b34f.PNG)

When I install nodejs in Version 8.17.0 and npm Version 4 or latest of 4, i get following Error while installing yo
Please see https://github.com/yeoman/yo/issues/665

How can I then setup an Environment for SPFX and SharePoint 2019 on prem? Which node and npm versions can I use?

**Comment by StfBauer** [comment]
@Link631 There are two things that have nothing to do with each other:

The first screenshot means that your project is capable of providing all features that were available at the time 1.4.1 came out, so no newer features or versions are supported on on-premises 2019.

The other thing is the generator as well as the build chain which is 1.11 that requires NodeJS 10.

So what happens is you create on NodeJS 10 a new project in the 1.11 generator, you get a project that then uses all the dependencies of 1.4.1. You build and bundle your solution and it will be with the feature set of 1.4.1 but this happens all under NodeJS 10.

If you would use the pure Microsoft generator 1.4.1 then you have to install NodeJS 6.x or 8.x but not with newer generators, those are perfectly fine to run under NodeJS 10.

So don't try to run the current generator on 6.x or 8.x, cause it is not supported and also not needed for any of your on-premises projects with a newer generator.

I know it's complicated but I hope this makes sense to you. Please feel free if you have further questions.

**Comment by Link631** [comment]
@StfBauer 
Thanks for your reply.

Do you see any Chance of getting an spfx project generated for SharePoint 2019 on prem with react 16.x? Currently I have react 15.x included and i would like to use fluent ui, which is possible only with react 16...

Thanks

**Comment by StfBauer** [comment]
Sadly not this part is managed by Microsoft and until they ship a newer version to SharePoint 2019. Honestly, I doubt this will happen.

**Comment by Link631** [comment]
@StfBauer 
thanks again:-)
I encounterd one more Problem / Question:
We want to connect custom spfx webparts with default list view webparts through dynamic data. I found out that dynamic data was introduced with SharePoint Framework 1.7.

Do you have any Idea how it can be possible, to trigger out of box listviews filter throughout a custom spfx webpart in 2019?
In onprem i would try to make use of dynamic data...

Thanks.

**Comment by juliemturner** [comment]
@Link631 -- As you point out Dynamic Data was introduced with version 1.7 of the SharePoint Framework, unfortunately support for SharePoint 2019 is limited to version 1.4, therefore you cannot create a dynamic data web part for SharePoint 2019.

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2019-support

**Comment by Link631** [comment]
Thanks for your answers :-)
