### ISSUE TITLE
--analyze is not working.

### ISSUE THREAD

**Issue by gauravgoyal5** [pnp/generator-spfx#303]
#### General Information
* [X] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [X] ReactJS

#### What Version you are running?
* NodeJS: 10.24.1
* NPM: 6.14.12
* @pnp/spfx: 1.16.1
*  @microsoft/generator-sharepoint@1.11.0
* gulp@3.9.1 
* pnpm@5.18.2 
* spfx-fast-serve@3.0.0 
* yo@3.1.0

#### Describe your problem
I am trying to run command "gulp serve --analyze" & getting the message :
![image](https://user-images.githubusercontent.com/6926513/121783138-a8c13a00-cbca-11eb-9bde-c22a4652f5b2.png)

**Comment by StfBauer** [comment]
spfx-fast-serve - is not supported by this generator, which could be a potential issue. Please try to create a project without this option and post the gulp file in your ticket.

Thank you.

**Comment by gauravgoyal5** [comment]
OK Thanks. rest others are working.
