### ISSUE TITLE
SPFx extension stopped working with no action from our side

### ISSUE THREAD

**Issue by rpochepovich** [pnp/generator-spfx#340]
#### General Information
* [ X] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS:   v16.10.0
* NPM:       7.24.0
* @pnp/spfx: 
* -> .\
`-- (empty)

#### Describe your problem
WE have a supprt ticket opened for that issue as follows (please see more information on MS Support findings below the dash line)
•	Microsoft Support [Case #:36134853]
•	Created on: Tuesday, April 25, 2023 9:38 AM
•	Description: We have custom SPFx extension developed and deployed for us by 3rd party vendor, Microsoft Partner. That extension worked as expected for about a year and some time ago stopped working without any actions taken from our side. That extension creates a link in Top Navigation and is supposed to show a drop down of item choices on mouse over. When the Intranet page where extension is hosted loads, DevTols show the following error (the GUID in the error is of the SPFx extension that stopped working and the URL of the sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js:70:1453258 is: https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js ): ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]] sp-pages-assembly_en-us_9bb00ad5e643999a6f8283c7d40ebf42.js:70 Uncaught (in promise) Error: Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer.6aa27935-d4df-42d5-a14e-92ef523a05f5'. Error information is 'Extension failed to initialize for componentId "6aa27935-d4df-42d5-a14e-92ef523a05f5".'. at sp-pages-assembly_en-us_9bb00ad5e643999a6f8283c7d40ebf42.js:70:1453258 at async Promise.all (index 0)
------------------------------------------------------------------------------------------------------------------------------
Shruti from SharePoint development team (Microsoft Premier Support <msprmsup@microsoft.com>  [Case #:36134853]) spent a lot of time troubleshooting and reproducing the issue in her environment, using code we provided. She built web part and the extension locally. Below is the citation from her latest email describing the status of the issue:
>>>>>>>>>>>>
I had an opportunity to spend multiple days with the copy of your code and get it to build in my lab. I do not see an scss file and that is where the package building fails. Is this the original code packaged and deployed?

Apart from that just taking the packaged solution file from your environment does not render the webpart.  Now again since the webpart does work for you and it renders alright but only the app customizer throwing the error, at this point it is very good idea to engage directly with our Product Team. It is best not to delay here as I did spend significant time trying to rebuild your solution. 

I reviewed the code and it looks alright to me. I see we are using pnp here. It is possible something has changed with pnp which could be resulting in this behavior. Pnp is a community support directly supported by our Product Team directly on the Github thread here. 
>>>>>>>>
I think it would be useful for you to connect to Shruti for more information as she already has a lot of useful information that would help to find and fix the issue.

**Comment by StfBauer** [comment]
Please submit your issue - https://github.com/SharePoint/sp-dev-docs/issues/new/choose
