### ISSUE TITLE
Generator Doesn't work

### ISSUE THREAD

**Issue by araver** [pnp/generator-spfx#72]
#### General Information
* [X] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: 8.11.3
* NPM: 6.4.1
* @pnp/spfx: 1.0.1

#### Describe your problem
Yeoman isn't recognizing this as a generator package. The solution is installed globally, but yo @pnp/spfx doesn't work nor does it list the package when just running yo. 
![image](https://user-images.githubusercontent.com/31546277/45517592-de137180-b76b-11e8-95a2-e73202c85f22.png)

![image](https://user-images.githubusercontent.com/31546277/45517685-39456400-b76c-11e8-8288-5423199becf2.png)

**Comment by StfBauer** [comment]
Thank you for letting us know. It seems like there was a problem with the publishing of the npm package.

Can you please update the generator with the following command:

```sh
npm install -g @pnp/generator-spfx@latest
```

The install version should then be 1.0.2.

Sorry for inconvenience.
