### ISSUE TITLE
Error creating project: throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by pkbullock** [pnp/generator-spfx#84]
#### General Information
* [x] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [X] HandlebarsJS

#### What Version you are running?
* NodeJS: v8.11.4
* NPM: 6.4.1
* @pnp/spfx: @pnp/generator-spfx@1.1.0

#### Describe your problem

Tried to create a new project with Handlebars but when creating an error was throw.
I will paste in error block

##### ERROR BLOCK

   create src\webparts\helloWorld\HelloWorldWebPart.manifest.json
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.getComponentManifest (C:\Users\PaulBullock\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\lib\util.js:194:119)
    at Object.deployTemplates (C:\Users\PaulBullock\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\lib\util.js:318:32)
    at module.exports.install (C:\Users\PaulBullock\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\generators\handlebars\index.js:46:14)
    at Object.<anonymous> (C:\Users\PaulBullock\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\yeoman-generator\lib\index.js:424:27)
    at C:\Users\PaulBullock\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\PaulBullock\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\PaulBullock\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\yeoman-generator\lib\index.js:425:13)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)

##### Full Command History to Reproduce

PS C:\git\play> yo @pnp/spfx
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    _____       _____          _____ _____  ______
   |████▄\      |████▄\      /▄█████|█████\|██████|
   |█|__█| __   |█|__█|      |█(___ |█|__)█|█|____  __
   |████▀/█▄██▄\|████▀/       \▀██▄\|█████/|██████\/▄▀
   |█|   |█▀  ▀█|█|           ____)█|█|    |█|   >██<
   |█|   |█|  |█|█|          |█████/|█|    |█|  ▄▀/\▀▄
█████████████████████████████████████████████████████████

 Generator:     PnP Community SPFx Generator
 Author:        Office 365 / SharePoint PnP Core Team
 Contributors:  Stefan Bauer, Chris Kent
 Version:       1.1.0

 Based on  @microsoft/generator-sharepoint version: 1.6.0

? Choose your framework Handlebars
? Which libraries to include pnpjs, PnP Property Controls

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |      Welcome to the      |
   `---------´   |  SharePoint Client-side  |
    ( _´U`_ )    |    Solution Generator    |
    /___A___\    '--------------------------'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Let's create a new SharePoint solution.
? What is your solution name? Test-PnPGenerator
? Where do you want to place the files? Create a subfolder with solution name
? Do you want to allow the tenant admin the choice of being able to deploy the solution to all sites immediately without
 running any feature deployment or adding apps in sites? No
? Which type of client-side component to create? WebPart
Add new Web part to solution test-pn-p-generator.
? What is your Web part name? HelloWorld
? What is your Web part description? HelloWorld description

---
Paul

**Comment by phawrylak** [comment]
This error is related to creating solution in subfolder. I got it too. I have fixed it in my changes for Angular Elements, but I can make a pull request only with this fix tomorrow.

**Comment by StfBauer** [comment]
Would be great I guess I need to extend the tests a bit. I guess the tests don't cover this up front now.
Pretty uncommon in regular Yeoman generator to create the folder in the generator.

Thank you @phawrylak

**Comment by StfBauer** [comment]
@pkbullock Thank you for the documentation update. Have you tried it to create a new SharePoint Solution without a folder?

**Comment by pkbullock** [comment]
@StfBauer lol, trust me to do things differently. The generator works if I avoid the "Create a subfolder with solution name" option. Thanks for this. Very nice to see Handlebars in SPFX too!

**Comment by StfBauer** [comment]
@pkbullock thank you for confirmation will look how I get this in the testing scenarios. It might not be that easy. ;)

**Comment by StfBauer** [comment]
@pkbullock issue should be fixed now in version 1.2.0

**Comment by pkbullock** [comment]
Thanks @StfBauer this is fixed. Nice work!

**Comment by StfBauer** [comment]
Wasn‘t me 😉

@phawrylak fixed it.
