### ISSUE TITLE
ReferenceError: watchVueFiles is not defined

### ISSUE THREAD

**Issue by AJIXuMuK** [pnp/generator-spfx#98]
#### General Information
* [x] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS
* [x] VueJS

#### What Version you are running?
* NodeJS: 8.12.0
* NPM: 6.4.1
* @pnp/spfx:  1.3.0

#### Describe your problem
>--------------- DELETE THIS BEFORE SUBMITTING ---------------

```bash
gulp
C:\Alex\Work\spfx\tests\pnp-gen-13\gulpfile.js:81
build.rig.addPreBuildTask(watchVueFiles);
                          ^

ReferenceError: watchVueFiles is not defined
    at Object.<anonymous> (C:\Alex\Work\spfx\tests\pnp-gen-13\gulpfile.js:81:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (C:\Users\leter\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\leter\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:198:16)
    at module.exports (C:\Users\leter\AppData\Roaming\npm\node_modules\gulp\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> (C:\Users\leter\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:190:9)
    at C:\Users\leter\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:164:9
    at C:\Users\leter\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:108:14
    at C:\Users\leter\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:36:12
    at C:\Users\leter\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:47:7
```

**Comment by StfBauer** [comment]
Thank you @AJIXuMuK

**Comment by sps-smith** [comment]
I am experiencing the same issue, but only with spfx projects targeting Framework extensions. Framework webparts work ok. There is a difference in the gulpfile.js config entries. See below

### **Webpart solution gulpfile entry**
```
// marker to check if custom watch is already registered
// used to prevent watch bubbling
let customWatchRegistered = false;

let watchVueFiles = build.subTask('watch-vue-files', function (gulp, buildOptions, done) {
    // register watch only on first run
    if (!customWatchRegistered) {

        // on change of *.vue files
        gulp.watch('./src/**/*.vue', event => {
            // copy empty index.ts onto itself to launch build procees
            gulp.src('./src/index.ts')
                .pipe(gulp.dest('./src/'));
        });

        // after watch is registered don't register again
        customWatchRegistered = true;

    }

    done();
});

build.rig.addPreBuildTask(watchVueFiles);
```
----------------------------------------------------------------------
### **Extension solution gulpfile entry**
```
// register custom watch for Vue.JS files
// copy of '.vue' files will be handled by 'copy-static-assets.json'
gulp.watch('./src/**/*.vue', event => {
    // copy empty index.ts onto itself to launch build procees
    gulp.src('./src/index.ts')
        .pipe(gulp.dest('./src/'));

});
build.rig.addPreBuildTask(watchVueFiles);

```
I will copy the missing entries from the webpart solution to the extension to see if that works

**Comment by sps-smith** [comment]
Adding the entries from the webpart project to the extension fixed the issue for me. I guess it just needs to be added to the scaffolding process.

**Comment by AJIXuMuK** [comment]
@sps-smith do you use Vue.js as framework or any other?
There is no difference in gulpfile.js for extensions and web parts.
My guess is that your web part project has been created using prev version of the generator.

But, anyway, the issue has been resolved in #99 and should be included in the next version.

Currently `watchVueFiles` task is not needed as we're just 'subscribing' `gulp.watch` to monitor changes in .vue files.

**Comment by AJIXuMuK** [comment]
@sps-smith yes, right now the issue is redolved in dev branch only. There was no version published after the fix. But it will be included in the next version.

**Comment by StfBauer** [comment]
New version with fix will be published later today.
